### ISSUE TITLE
Success Criterion 2.5.2: Pointer Cancellation (Level A)

### ISSUE THREAD

**Issue by maryjom** [w3c/wcag2ict#124]
From [Success Criterion 2.5.2](https://www.w3.org/TR/WCAG22/#pointer-cancellation):

>For [functionality](https://www.w3.org/TR/WCAG22/#dfn-functionality) that can be operated using a [single pointer](https://www.w3.org/TR/WCAG22/#dfn-single-pointer), at least one of the following is true:
>
>**No Down-Event**
>The [down-event](https://www.w3.org/TR/WCAG22/#dfn-down-event) of the pointer is not used to execute any part of the function;
>
>**Abort or Undo**
>Completion of the function is on the [up-event](https://www.w3.org/TR/WCAG22/#dfn-up-event), and a [mechanism](https://www.w3.org/TR/WCAG22/#dfn-mechanism) is available to abort the function before completion or to undo the function after completion;
>
>**Up Reversal**
>The up-event reverses any outcome of the preceding down-event;
>
>**Essential**
>Completing the function on the down-event is [essential](https://www.w3.org/TR/WCAG22/#dfn-essential).
>
>NOTE
>Functions that emulate a keyboard or numeric keypad key press are considered essential.
>
>NOTE
>This requirement applies to web content that interprets pointer actions (i.e. this does not apply to actions that are required to operate the user agent or assistive technology).

##### Guidance When Applying Success Criterion 2.5.2 to Non-Web Documents and Software

This applies directly as written, and as described in [Intent from Understanding Success Criterion 2.5.2](https://www.w3.org/WAI/WCAG22/Understanding/pointer-cancellation.html#intent) (also provided below), making changes to the notes by replacing “web content” with "content" or “non-web software” and removing "user agent" as an excepted case for non-web software.

With these substitutions, the notes would read: 
(for non-web documents)

**NOTE 1**
Functions that emulate a keyboard or numeric keypad key press are considered essential. 

**NOTE 2**
This applies to **[content]** that interprets pointer actions (i.e. this does not apply to actions that are required to operate the user agent or assistive technology).

**NOTE 3**
Applicability of this Success Criterion would be limited to document types where a document author can add content that interprets pointer actions and control which events are used for executing functionality. For example, prototyping tools used to design software.

(for non-web software)

**NOTE 1**
Functions that emulate a keyboard or numeric keypad key press are considered essential.  Additional essential functions for **[non-web software]** are changing the device to a user-ready state or providing additional contextual options, as well as situations where the underlying platform restricts software from knowing pointer state changes (such as security used for encryption purposes).

**NOTE 2**
This requirement applies to **[non-web software]** that interprets pointer actions (i.e. this does not apply to actions that are required to operate assistive technology).

**NOTE 3** 
Non-web software applications are not responsible for pointer actions required to operate the underlying user agent or platform software.

***
In the section "Glossary Items with Specific Guidance" add these definitions:

### dfn-down-event

From the [WCAG 2.2 definition for down-event](https://www.w3.org/TR/WCAG22/#dfn-down-event):

>**down-event**
>platform event that occurs when the trigger stimulus of a pointer is depressed
>
>The down-event may have different names on different platforms, such as "touchstart" or "mousedown".

#### Guidance When Applying “down-event” to Non-Web Documents and Software

This applies directly as written and as described in the WCAG 2.2 glossary.
 
**NOTE** 
The down-event may have different names on different platforms. For example **["PointerPressed” or “mousedown”]**. 

### dfn-up-event

From the [WCAG 2.2 definition for up-event](https://www.w3.org/TR/WCAG22/#dfn-up-event):

> **up-event**
> platform event that occurs when the trigger stimulus of a pointer is released
> 
> The up-event may have different names on different platforms, such as "touchend" or "mouseup".

#### Guidance When Applying “up-event” to Non-Web Documents and Software

This applies directly as written and as described in the WCAG 2.2 glossary.
 
**NOTE**
The up-event may have different names on different platforms. For example **[“PointerReleased” or “mouseup”]**.

**Comment by mitchellevan** [comment]
<blockquote>NOTE 1<br>
Functions that emulate a keyboard or numeric keypad key press are considered essential.  Additional essential functions for [non-web software] are changing the device to a user-ready state or providing additional contextual options, as well as situations where the underlying platform restricts software from knowing pointer state changes (such as security used for encryption purposes).
</blockquote>

I prefer "Waking a device from sleep mode," which was mentioned in email discussion and is easier to understand than "changing the device to a user-ready state." (I googled "user ready state" and "user-ready state" and I didn't find it as a term of art.)

I would be fine including something akin to "additional contextual options," but this phrase could mean most disclosure widgets, which was probably not the intent. @samogami can you suggest a more specific example?

From @pday1's email:

> Closed system: another example where it could cause issues is where a touchscreen is encrypted for security (e.g. entering a personal identification number onscreen). In this case, the underlying software may not be allowed to know some of these state changes, and therefore we either classify this in the essential functions note, or as another example in Sam's closed functionality examples

Whichever layer of the software implements the pointer micro-interactions can be responsible for meeting this criterion, without any expectation of exposing those events to a different layer of the software. The cited example of entering a personal identification number is a type of on-screen key press, which is already listed as essential, so I don't see a need to add this additional example. Phil, can you suggestion a different exception example (not an on-screen key press) in the context of a software security function?

Pending such other examples, I propose the following edit.

<blockquote>NOTE 1<br>
Functions that emulate a keyboard or numeric keypad key press are considered essential.  An additional essential function <ins>example</ins> for [non-web software] is <ins>waking a device from sleep mode</ins>.
</blockquote>

**Comment by samogami** [comment]
@mitchellevan sleep mode is only one. two other examples of non user ready (ready state) would be **power saver mode** or **low power state** both are are used to meet environmental energy usage requirements.

**Comment by bruce-usab** [comment]
+1 with two additions above.

> NOTE 1
> Functions that emulate a keyboard or numeric keypad key press are considered essential.  An example of essential functionally  for [non-web software] are features for meeting environmental energy usage reequipments (like waking a device from sleep mode, power saver mode, and low power state).

**Comment by pday1** [comment]
I'm happy to incorporate these changes

DRAFT RESOLUTION: Merge 2.5.2 Pointer Cancellation into the editor’s draft with the changes Mitchell proposed and Bruce’s update to Note 1 (text above).  

NOTE 1 Functions that emulate a keyboard or numeric keypad keypress are considered essential. Examples of essential functionality for [non-web software] are features for meeting environmental energy usage requirements (like waking a device from sleep, power saver mode, and low power state).

**Comment by maryjom** [comment]
AG WG [surveyed](https://www.w3.org/2002/09/wbs/35422/WCAG2ICT-second-content-review-by-AGWG/results) and approved this on 11 April. Closing.
