### ISSUE TITLE
Finalizing Note: Last check/update to the list of acknowledgements

### ISSUE THREAD

**Issue by maryjom** [w3c/wcag2ict#131]
Before we publish the the last version, update all of the Acknowledgements sub-section's lists of contributors to include:
- [x] Update any information on TF participants that changed affiliation or status during the WCAG2ICT development. 
- [x] Any new WCAG2ICT TF participants
- [x] AG WG members that have responded to surveys, opened issues, and/or commented on our issues as we've been developing content.
- [x] Ensure contributing funders content is current.

**Comment by pday1** [comment]
@ChrisLoiselle  to work on participants in acknowledgements
Task force participants - haven't been working on doc
Name them in separate section to active contributors (listed participants instead of active contributors) - Chris to create PR

**Comment by ChrisLoiselle** [comment]
@pday1 @maryjom The following was merged https://github.com/w3c/wcag2ict/pull/346 , so based on this , I feel this is up to date as it can be. I'll edit per Daniel's heading structure request is.

**Comment by ChrisLoiselle** [comment]
@daniel-montalvo @maryjom I'd need the list of backups to include, however had reformatted the wording of the heading levels per @daniel-montalvo 's request. @pday1

**Comment by ChrisLoiselle** [comment]
@daniel-montalvo do you need me to update in any way ? Are we waiting until right before publication to update further?

**Comment by daniel-montalvo** [comment]
@ChrisLoiselle 
Yes, we should do this right before publishing. We should leave this open for now.

**Comment by mitchellevan** [comment]
@Lboniello, do you want to keep your TPGi affiliation? https://w3c.github.io/wcag2ict/#acknowledgements

**Comment by ChrisLoiselle** [comment]
@maryjom @pday1 @daniel-montalvo I had done work on this back in May https://github.com/w3c/wcag2ict/pull/358 , is there anything else you want me to do with this? I can email the entire group , but thought this was taken care of. If it is a formality, we could close issue. Not sure what else you'd like me to do here.

**Comment by maryjom** [comment]
@ChrisLoiselle I'm leaving this open just in case there's someone from AGWG who reviews or comments this round of review. We'll add them just before final publication.

**Comment by maryjom** [comment]
I've just updated the list of contributors. @daniel could you please ensure the [Enabling Funders](https://w3c.github.io/wcag2ict/#enabling-funders) content is current?

**Comment by maryjom** [comment]
Acknowledgements updates are complete.
