### ISSUE TITLE
Success Criterion 2.5.1: Pointer Gestures (Level A)

### ISSUE THREAD

**Issue by samogami** [w3c/wcag2ict#143]
From [Success Criterion 2.5.1](https://www.w3.org/TR/WCAG22/#pointer-gestures):

>All [functionality](https://www.w3.org/TR/WCAG22/#dfn-functionality) that uses multipoint or path-based gestures for operation can be operated with a [single pointer](https://www.w3.org/TR/WCAG22/#dfn-single-pointer) without a path-based gesture, unless a multipoint or path-based gesture is [essential](https://www.w3.org/TR/WCAG22/#dfn-essential).
>
>**NOTE**
>This requirement applies to web content that interprets pointer actions (i.e. this does not apply to actions that are required to operate the user agent or assistive technology).

##### Guidance When Applying Success Criterion 2.5.1 to Non-Web Documents and Software

- This applies directly as written, and as described in [Intent from Understanding Success Criterion 2.5.1](https://github.com/orgs/w3c/projects/13?pane=issue&itemId=13121605) 

> **Note:**  Applicability of this success criterion would be limited to software and non-web documents where interactive gesture capabilities are available for authors to add. Examples included but not limited to prototyping tools used to design software.

**Comment by detlevhfischer** [comment]
The differentiation of pointer gestures and dragging movements has always be difficult. Mobile apps frequently employ horizontal tile sliders that require an initial horizontal pointer movement (left **or** right) in order to differentiate the gesture from the system gesture for vertical scrolling of the view. Since no **specific** direction of the gesture is needed to engage the element (**but** it must be roughly horizontal), one could argue that the gesture to move such sliders should not be classed as pointer gesture according to 2.5.1, but as dragging movement (which will require alternatives only in WCAG 2.2, if 2.5.7 Dragging Movements is adopted).

Should WCAG2ICT have a note to help people differentiate between Pointer Gestures and Dragging Movements?
See also my community reach-out here: https://webaim.org/discussion/mail_message?id=48920

**Comment by detlevhfischer** [comment]
Done: https://github.com/w3c/wcag/pull/3148

**Comment by GreggVan** [comment]
I'm not sure the problem cited above is a problem.     Since everything is supposed to be doable from the keyboard, the fact that that dragging motion requires two gestures --  (one horizontal to select and then vertical to drag down) is not a problem.  Both select and move down should be accomplish-able from the keyboard. 

Perhaps we just need to point out that the drag horizontal then vertical is not a path dependent gesture - but actually two chained gestures.    But I don't think even that is really necessary.  

Perhaps I am missing the point here.  What is the problem that the added note solves? 

ALSO  - where doe the comment  " dragging movement (which will require alternatives only in WCAG 2.2, " come from? A requirement that everything (including dragging) be operable from the keyboard has been around since WCAG 1.0.  
Again - am I missing the message?

**Comment by patrickhlauke** [comment]
> Perhaps I am missing the point here. What is the problem that the added note solves?

the point is that people are often confused about what counts as strictly path-based, and what is more loosely a dragging motion

**Comment by mraccess77** [comment]
@GreggVan the goal of addressing pointer gesture issues on WCAG 2.1 and 2.2 was in addition to keyboard requirements.  The aim is to help people with motor disabilities on devices such as mobile where they may not have a keyboard interface available.   I know that an on-screen keyboard is a keyboard interface - however, current mobile platforms don't support bringing up such on-screen keyboards, often keystrokes aren't passed through on mobile the same as desktop and with the small screen size an on-screen keyboard would make the viewport cut in half for many.  So, the premise was to make pointer gestures more accessible regardless of keyboard interface.

**Comment by maryjom** [comment]
I'm wondering if this SC can draw from the notes done (and approved by the AG WG) for [2.5.2 Pointer Gestures](https://deploy-preview-148--wcag2ict.netlify.app/#pointer-cancellation) where notes for non-web documents and non-web software are handled separately. I've copied in and made the adjustments for this SC.

This applies directly as written, and as described in [Intent from Understanding Success Criterion 2.5.1](https://www.w3.org/WAI/WCAG22/Understanding/pointer-gestures#intent) (also provided below), making changes to the notes by replacing “web content” with "content" or “non-web software” and removing "user agent" as an excepted case for non-web software.

(non-web documents)
NOTE
This requirement applies to **[content]** that interprets pointer actions (i.e. this does not apply to actions that are required to operate the user agent or assistive technology).

NOTE
Applicability of this Success Criterion would be limited to document types where a document author can add content that interprets pointer actions and control which events are used for executing functionality. For example, prototyping tools used to design software.

(non-web software)
NOTE
This requirement applies to **[non-web software]** that interprets pointer actions (i.e. this does not apply to actions that are required to operate assistive technology).

NOTE
Non-web software applications are not responsible for pointer actions required to operate the underlying user agent or platform software.

**Comment by mitchellevan** [comment]
Non-web document NOTE 2:

> Applicability of this Success Criterion would be limited to document types where a document author can add content that interprets pointer actions and control which events are used for executing functionality. For example, prototyping tools used to design software.

The word "limited" makes it sound like we're trying to change the applicability. I believe the intention is only that such pointer actions are less frequent in documents. Proposed:

> Multipoint and path-based gestures are less common in documents. An example where a document author could add such gestures is an interactive prototype document created in a software design tool.

**Comment by mitchellevan** [comment]
Non-web software notes:

> NOTE
> This requirement applies to [non-web software] that interprets pointer actions (i.e. this does not apply to actions that are required to operate assistive technology).
> 
> NOTE
> Non-web software applications are not responsible for pointer actions required to operate the underlying user agent or platform software.

Nit: Combine these two notes into one.

> NOTE
> This requirement applies to [non-web software] that interprets pointer actions (i.e. this does not apply to actions that are required to operate <ins>[underlying platform software] or</ins> assistive technology).

**Comment by maryjom** [comment]
Agreed in the 27 April meeting on:
From [Success Criterion 2.5.1](https://www.w3.org/TR/WCAG22/#pointer-gestures):

>All [functionality](https://www.w3.org/TR/WCAG22/#dfn-functionality) that uses multipoint or path-based gestures for operation can be operated with a [single pointer](https://www.w3.org/TR/WCAG22/#dfn-single-pointer) without a path-based gesture, unless a multipoint or path-based gesture is [essential](https://www.w3.org/TR/WCAG22/#dfn-essential).
>
>**NOTE**
>This requirement applies to web content that interprets pointer actions (i.e. this does not apply to actions that are required to operate the user agent or assistive technology).

##### Guidance When Applying Success Criterion 2.5.1 to Non-Web Documents and Software

This applies directly as written, and as described in [Intent from Understanding Success Criterion 2.5.1](https://www.w3.org/WAI/WCAG22/Understanding/pointer-gestures#intent) (also provided below), making changes to the notes by replacing “web content” with "content" or “non-web software” and removing "user agent" as an excepted case for non-web software.

(non-web documents)
NOTE
This requirement applies to **[content]** that interprets pointer actions (i.e. this does not apply to actions that are required to operate the user agent or assistive technology).

NOTE
Multipoint and path-based gestures are less common in documents. An example where a document author could add such gestures is an interactive prototype document created in a software design tool.

(non-web software)
NOTE
This requirement applies to **[non-web software]** that interprets pointer actions (i.e. this does not apply to actions that are required to operate the **[underlying platform software]** or assistive technology).

**Comment by maryjom** [comment]
@pday1 @ChrisLoiselle Whomever gets to this first...please implement in the document. Thanks!

**Comment by pday1** [comment]
Thanks @ChrisLoiselle for doing this so quickly. I've approved PR #150

**Comment by maryjom** [comment]
I added in my changes to the PR and merged.

**Comment by ChrisLoiselle** [comment]
@maryjom  I see this as open, should we close or have it remain open?

**Comment by maryjom** [comment]
@ChrisLoiselle I was waiting to close the issues for the newest added SCs until the AG WG reviewed and approved them.

**Comment by maryjom** [comment]
The TF reached [consensus on the guidance for SC 2.5.1](https://www.w3.org/2023/04/27-wcag2ict-minutes#t05) on 27 April. The AG WG [reviewed 2.5.1](https://www.w3.org/2002/09/wbs/55145/WCAG2ICT-Third-content-review-by-AGWG2/results#xq10) in the 3rd content review and approved the content on 25 July.
