### ISSUE TITLE
1.4.10 Reflow - Guidance & notes for non-web documents

### ISSUE THREAD

**Issue by maryjom** [w3c/wcag2ict#159]
Split Issue #98 to cover individual aspects for 1.4.10 Reflow. This issue is for discussion of its application to **non-web documents**. I have copied the draft notes from my initial draft and comments on that specific aspect from issue 98.

## Draft notes for non-web documents (Mary Jo)
>For non-web documents:
>
>Note 1: If the document type or the user agent don't provide reflow capabilities, then the document content requires two-dimensional layout for usage or meaning and would meet the exception of this Success Criterion.

### Mitchell's proposal:
Issue: Some PDF user agents provide reflow and others do not. Some "document types" of PDF support reflow and others do not. Need to clarify this situation.

Proposed: If there is no available user agent for the document type, such that the combination of the user agent and the document type support reflow, then the two-dimensional layout exception applies.

<blockquote>For non-web documents:<br><br>Note 1: If <ins>a document type and its available user agents</ins> don't provide reflow capabilities, then the document content requires two-dimensional layout for usage or meaning and would meet the exception of this Success Criterion.
</blockquote>

Relevant: [WCAG Issue 814 What is sufficient for SC 1.4.10?](https://github.com/w3c/wcag/issues/814)

### Bruce’s proposal:
I came away (from the [4 May meeting](https://www.w3.org/2023/05/04-wcag2ict-minutes#t05)) thinking the note should be more narrow, and also make reference to the fact that not all file format are accessibility supported.  I propose for consideration something like:
 
> Note 1: An example of non-web documents which require two-dimensional layout for usage are nature photographs.
> 
> Note 2:  Not all document types support reflow, and some document types do not support reflow on some user agents.  Such limitations are not under author control, but that does not mean that the content requires two-dimensional layout for usage or meaning.  Such limitations might mean that the document type is not [accessibility supported](https://www.w3.org/TR/WCAG22/#dfn-accessibility-supported).
 
### Mary Jo’s adjustment to Bruce’s proposal:
 
Note 1: Examples of non-web documents which require two-dimensional layout for usage are nature photographs or documents intended only for printing or archival of print format material. 
 
Note 2: Reflow may not be [accessibility supported](https://www.w3.org/TR/WCAG22/#dfn-accessibility-supported) by all document types and user agents. Such limitations are not under author control, but this does not mean the document requires two-dimensional layout for usage or meaning.
 
### Mike Gower’s comment:
_(Referring to Bruce's proposal and Mary Jo's adjustment)_
 
Neither version of Note 1 makes it clear to me 1) why a nature photograph would be excluded, nor 2) why it would be considered a non-web document.
So i think you need a bit more explanation in those notes. First, there is no reason that a photograph cannot be reduced to fit the available space. It may become so small that it is essentially a thumbnail which cannot serve the same purpose as a high-resolution archival photo, but there is no reason that the representation of any image cannot fit in a confined space.
WCAG uses the phrase
>images required for understanding (such as maps and diagrams),
 
In the context of WCAG2ICT, I'd be inclined to work in some concept of "original size" or even "high resolution" to try to tackle the context that information must be presented beyond the physical dimensions of a device to achieve its intended function. I assume that's where you were going with "archival", but I think it needs a bit more. I also think an example of an actual non-web document format would be useful.
Maybe something like:
>Examples of non-web documents which require two-dimensional layout for usage, and so require horizontal scrolling, are high resolution archival photographs or documents stored in a ___ system.
 
### Mike Pluke’s comment regarding the proposals
 
The original WCAG note is all about **content** that "requires two-dimensional layout", and allowing that type of content not to be reflowed. In my view, it was never intended to allow user agents or document types to not reflow content **just because they cannot**. But that is what the note seems to be saying when it says that all content that such user agents or document types encounter **"requires two-dimensional layout"**.

**Comment by mitchellevan** [comment]
> Note 1: If a document type and its available user agents don't provide reflow capabilities, then the document content requires two-dimensional layout for usage or meaning and would meet the exception of this Success Criterion.

My main contribution here was to change "or" to "and", trying to be less permissive, not more. I would be fine with tossing out this whole note, if the consensus is to put responsibility for 1.4.10 on content authors that is more challenging to achieve on some platforms than it is on web.

**Comment by maryjom** [comment]
I guess the point I wanted to make is that the ability to reflow is mainly dependent on the user agent or authoring tool to support it - in at least one mode of operation. Document authors would need to understand the capabilities of the user agents and what document authoring techniques to avoid that would prevent proper reflow of content by the user agent. If available user agents don't support reflow or has bugs in the reflow capabilities, this SC can't be met and a different accessible document format would need to be made available to meet this SC.  So maybe that is what the note should say. 

So I propose:
Note: When user agents and authoring tools for a non-web document type do not provide support for content reflow, it may not be possible for non-web documents of that type to meet this success criterion.

**Comment by maryjom** [comment]
The note to add more examples will not be added per the 6 July consensus of the TF. What will be added is the following note:

(non-web documents)
**NOTE** If a non-web document type and its available user agents do not support reflow, it may not be possible for a document of that type to meet this success criterion.
