### ISSUE TITLE
WCAG2ICT Project: Update Abstract

### ISSUE THREAD

**Issue by maryjom** [w3c/wcag2ict#16]
The original 2013 WCAG2ICT Abstract was:

This document, “Guidance on Applying WCAG 2.0 to Non-Web Information and Communications Technologies (WCAG2ICT)” describes how the [Web Content Accessibility Guidelines (WCAG) 2.0](http://www.w3.org/TR/2008/REC-WCAG20-20081211/) [WCAG20](https://www.w3.org/TR/wcag2ict/#REF-WCAG20)] and its principles, guidelines, and success criteria can be applied to non-web Information and Communications Technologies (ICT), specifically to non-web documents and software. It provides informative guidance (guidance that is not normative and does not set requirements).

This document is a Working Group Note, and is part of a series of technical and educational documents published by the [W3C Web Accessibility Initiative (WAI)](http://www.w3.org/WAI/) and available from the [WCAG 2.0 Overview](http://www.w3.org/WAI/intro/wcag.php).

Updates needed in the Abstract:

- [x] Name of the document
- [x] Link to WCAG 2.2 
- [x] [Overview](https://www.w3.org/WAI/standards-guidelines/wcag/non-web-ict/) - previously a direct link to where the 2013 WCAG2ICT note link resided on the [WCAG 2 Overview](https://www.w3.org/WAI/standards-guidelines/wcag/) page, but now you need to use the "Applying to non-web ICT" navigation item on that page to go to the [WCAG2ICT Overview](https://www.w3.org/WAI/standards-guidelines/wcag/non-web-ict/) page. IMO, better to provide a direct link to that page instead.
- [x] Mention it is a "draft update" to the working group note

**Comment by ChrisLoiselle** [comment]
@maryjom

1.  since https://www.w3.org/TR/WCAG22/ is a candidate recommendation, did you want me to link to it yet and the overview?
2. By overview, did you mean https://www.w3.org/TR/WCAG22/#background-on-wcag-2 or something else entirely?
3. The abstract already links to the WCAG 2 Overview, https://www.w3.org/WAI/standards-guidelines/wcag/

**Comment by ChrisLoiselle** [comment]
This relates to pull https://github.com/w3c/wcag2ict/pull/87

**Comment by maryjom** [comment]
@ChrisLoiselle I wasn't really sure which overview to go to at the time I made this issue. I've updated the information at the top with the correct link - to the WCAG2ICT Overview page. So the link text and URL both need updating.

**Comment by maryjom** [comment]
See [survey](https://www.w3.org/2002/09/wbs/55145/WCAG2ICT-Abstract-change-log/) due 16 Feb.

**Comment by maryjom** [comment]
Content for this section was reviewed again and updated to be consistent/current with the document contents and status prior to FPWD publication.
