### ISSUE TITLE
WCAG2ICT Project: Update the W3C Technical Reports Index

### ISSUE THREAD

**Issue by maryjom** [w3c/wcag2ict#17]
When FPWD is being done, update the [Technical Reports index](https://www.w3.org/TR/).

- [x] Add in the new document
- [x] Create the new list of editors (Mary Jo Mueller, Chris Loiselle, and Phil Day)
- [x] Add link to the published version

**Comment by ChrisLoiselle** [comment]
@maryjom I've created a pull for contributors. When I'm on the main document in editor's draft, I do see the list of new list of editors, so would that information be pulled automatically in to https://www.w3.org/TR/ or are you saying we have an action item do create a list within the https://www.w3.org/TR/ process?

**Comment by ChrisLoiselle** [comment]
Per the editor's draft, I do see the link to the https://www.w3.org/TR/ per https://w3c.github.io/wcag2ict/#sotd

**Comment by maryjom** [comment]
@ChrisLoiselle This issue is about updating W3C's official list of technical reports so that the new WCAG2ICT appears there. That won't happen until we have a First Public Working Draft that goes out for wide (outside of W3C) review. If you use this link to [see the list of WCAG2ICT versions](https://www.w3.org/TR/?title=wcag2ict), you'll understand what I mean. I think Daniel or Michael will be the one to handle this issue, as doing this isn't in the WCAG2ICT document code - it's in a database of some sort.

**Comment by ChrisLoiselle** [comment]
@maryjom thanks, I see that you've unassigned me , thank you.

**Comment by maryjom** [comment]
This was done with the FPWD. However, the 2013 version of the document disappeared from the W3C TR index. See Issue #214.
