### ISSUE TITLE
WCAG2ICT Project: Update Introduction sections

### ISSUE THREAD

**Issue by maryjom** [w3c/wcag2ict#19]
Four sections to update, most of them will have minimal changes. Not sure we need to have the number of glossary terms, number of SC that apply. Just adds more maintenance once the rest of the document is done and for each release of WCAG.

- [x] Introduction
- [x] Excluded from scope
- [x] Document overview
- [x] Document conventions

**Comment by maryjom** [comment]
In the 26 January meeting, there was a [discussion](https://www.w3.org/2023/01/26-wcag2ict-minutes.html#t03) about the [survey on the Background section](https://www.w3.org/2002/09/wbs/55145/WCAG2ICTBackground/results). During that review, some changes were desired in the [Guidance in this Document](https://w3c.github.io/wcag2ict/#guidance-in-this-document) section.
- @mapluke  mentioned he'd like to see a warning regarding "set of documents" and "set of programs" and provided potential text in the survey.
- @maryjom mentioned there are other places in the document with similar language (e.g. SC that use "website" or "set of pages"), may want to be consistent.
- @GreggVan noted this section has text regarding how many SC were analyzed, apply, etc. which will need updating, if it's kept.

**Comment by ChrisLoiselle** [comment]
@maryjom  we can discuss this on our editorial meeting that you've accepted, thank you!

**Comment by ChrisLoiselle** [comment]
- Per https://www.w3.org/2002/09/wbs/55145/WCAG2ICTBackground/results , all requested comments per survey seem to be incorporated. 
- I'm not sure if we are tracking Gregg's comments on how many were analyzed or how many apply here, or if that is a separate edit. Happy to update, just didn't come across it in minutes or survey results to my knowledge. Please let me know. 

@maryjom

**Comment by maryjom** [comment]
@ChrisLoiselle I think that many of the changes will be something we do nearer to publication of the First Public Working Draft of the document.

**Comment by maryjom** [comment]
Additional updates needed in the document conventions section were made prior to FPWD publication.
