### ISSUE TITLE
Can a non-web software act as, or have, a conforming alternate version? Content needed

### ISSUE THREAD

**Issue by mitchellevan** [w3c/wcag2ict#196]
On today's Task Force call we discussed [whether a desktop GUI app can act as the conforming alternate version of a text application](https://github.com/w3c/wcag2ict/pull/172#discussion_r1268869557). We agreed not to answer this in context of text applications specifically, but instead consider adding WCAG2ICT content that addresses this question for all kinds of applications.

We should answer these aspects of the question:

* Can one non-web application act as a [conforming alternate version](https://www.w3.org/TR/WCAG/#dfn-conforming-alternate-version) of another non-web application, on the same or different operating system?
* Can a non-web application act as a conforming alternate version of a web application or vice versa?

We might also want to answer:

* Can one non-web document act as a conforming alternate version of another non-web document, of the same document format or a different document format?
* Can a non-web document act as a conforming alternate version of web pages, or vice versa?

This new WCAG2ICT content might take the form of word substitution and notes for the definition of "conforming alternate version".

**Comment by mitchellevan** [comment]
I recently [answered a similar question on the WAI Interest Group list](https://lists.w3.org/Archives/Public/w3c-wai-ig/2023AprJun/0055.html
). This part of my answer is relevant to the present issue:

> WCAG allows the possibility of a conforming alternate version <https://www.w3.org/TR/WCAG/#dfn-conforming-alternate-version>, [like Section 508] requiring all functionality and full conformance, and adding requirements on how users can reach the conforming and non-conforming versions. Whether native software could be a "page" for such purposes is not defined.

Thinking more about this, I believe the definition of "conforming alternate version" needs word substitution in WCAG2ICT like this:

<blockquote>
...at least one of the following is true:

* the conforming version can be reached from the non-conforming page<ins>, non-web application, or non-web document</ins> via an [accessibility-supported](https://www.w3.org/TR/WCAG/#dfn-accessibility-supported) [mechanism](https://www.w3.org/TR/WCAG/#dfn-mechanism), or
* the non-conforming version can only be reached from the conforming version, or
* the non-conforming version can only be reached from a conforming page<ins>, non-web application, or non-web document</ins> that also provides a mechanism to reach the conforming version
</blockquote>

The first bullet point above appears impossible for a non-conforming non-web application to meet, because the entire application would need to be conforming, which defeats the purpose. However, it seems possible that a conforming web page of an overall non-conforming website could link to a conforming software application.

The second and third bullet points above appear possible.

Of course, these same stringent conditions must also be met: 

> 2. provides all of the same information and [functionality](https://www.w3.org/TR/WCAG/#dfn-functionality) in the same [human language](https://www.w3.org/TR/WCAG/#dfn-human-language-s), and
> 3. is as up to date as the non-conforming content

I would argue that requiring the user to switch to a different operating system would always fail the "same functionality" requirement.

**Comment by mitchellevan** [comment]
A fundamental feature of almost all websites is that they are designed to work on more than one operating system. So requiring a user to switch from an inaccessible website to an accessible native app would also fail the "same functionality" requirement. An exception would be an [environment](https://www.w3.org/TR/UNDERSTANDING-WCAG20/conformance.html#uc-support-level-head), such as company, that mandates a single operating system for its intranet users.

**Comment by mraccess77** [comment]
I would think that software could have a non-conforming screen but another conforming screen/view in the software that can be reached from that screen that is non-conforming.  In my experience a "screen" or "view" is more akin to a page and the conforming alternatives shouldn't just be at the whole software level but within the software just like you can have a conforming alternative page and not require a whole separate website.

**Comment by maryjom** [comment]
We were having this discussion in the context of Text/Command line/ Terminal Emulator applications where a terminal emulator may have both a text-based version and a GUI version. There was text there to indicate that if the GUI was accessible, the text version wouldn't necessarily have to be.

**Comment by maryjom** [comment]
Some aspects of "conforming alternative version," such as having an "accessibility mode of operation," could be talked about if we decide to provide guidance on this. I don't think it would be acceptable to say having an accessible desktop app is a conforming alternate to an inaccessible mobile app (or vice versa). That is like saying to someone with a disability, "You can only access your banking when using your desktop computer - not by using the bank's mobile application." I recall conversations with US Federal agencies on this topic where they also didn't feel it would be acceptable either.

**Comment by maryjom** [comment]
Opened a Discussion #310 on this topic for the TF and others to weigh in on whether or not to address this in WCAG2ICT.

**Comment by bruce-usab** [comment]
+1 to @mraccess77 [comment](#issuecomment-1644752819) but I am hesitant to characterize non-web software providing suitable features for meeting accessibility requirements as <q>conforming alternative version</q> as I think this is just meeting accessibility requirements.  Introducing the concept of conforming alternative version in this context will be confusing.  It is just a conforming version.

**Comment by maryjom** [comment]
The Friday group had a discussion on 22 March. Since "conforming alternate version" is not used in this document, we won't address it in the Note.

**Comment by bruce-usab** [comment]
This comes up in the context of 508 all the time.  If the participants of this TF could provide some guidance, it would be much appreciate.  It is a difficult thing to come up with criteria for when an accessible website makes up for an inaccessible app (and vice versa) but if not members of this TF, who could do a better job of that?

**Comment by maryjom** [comment]
After the [discussion in the 18 April meeting](https://www.w3.org/2024/04/18-wcag2ict-minutes#t03), the TF decided to leave the current text regarding [Applying "conforming alternate version" to non-web documents and software](https://w3c.github.io/wcag2ict/#applying-conforming-alternate-version-to-non-web-documents-and-software) as-is, as doing any sort of interpretation would lead to us going beyond the WCAG2ICT TF scope. It is too complex a topic to handle with simple word substitutions. Current text in the editor's draft:

The guidance in this document does not use the term “conforming alternate version”.

See the section [Comments on Conformance](https://w3c.github.io/wcag2ict/#comments-on-conformance).

Since no document changes will be done, closing this issue.
