### ISSUE TITLE
How to assess Reflow on non-web content

### ISSUE THREAD

**Issue by mbgower** [w3c/wcag2ict#2]
Somewhat related to w3c/wcag#1550 , I have had a question from a developer working on a Windows desktop application about how to test and assess Reflow on non-web materials.
The [WCAG2ICT material ](https://www.w3.org/WAI/GL/wcag2ict/)has not been updated since 2013. On the web, one relies on the user agent to provide the zoom functionality. So it is easy to know how to assess.
What is the equivalent on a desktop?
@bruce-usab this applies in Revised 508 to software. Do you have any insight into how people are reporting against it?
@DavidMacDonald you feel that Reflow applies to non-web ICT in your https://www.davidmacd.com/WCAG/wcag2ict-21-discussion.html
Anyone have any idea how to assess?

**Comment by maryjom** [comment]
Moved to WCAG2ICT repository as the new TF will work to address issues tagged as WCAG2ICT from the WCAG repository.

**Comment by maryjom** [comment]
WCAG2ICT TF discussion on application of 1.4.10 Reflow to non-web software and documents is happening in the WCAG2ICT Issue #98 where we are discussing and drafting guidance content. Join in there if you wish to weigh in.

**Comment by maryjom** [comment]
The TF has published [guidance for Applying 1.4.10 Reflow to non-web documents and software](https://www.w3.org/TR/wcag2ict/#guidance-when-applying-success-criterion-1-4-10-to-non-web-documents-and-software) in its FPWD. If you have questions or comments on this guidance, please open a new issue.
