### ISSUE TITLE
Issues with links to 2013 version of the Note

### ISSUE THREAD

**Issue by maryjom** [w3c/wcag2ict#214]
The WCAG2ICT FPWD went out with a link of https://www.w3.org/TR/wcag2ict/ for the "latest published version". However, this broke a few points of access to the 2013 version that used to be found at that link. These will need to all be fixed:
- [x] When Viewing the 2013 Note, it says it is outdated which isn't yet the case until the new Note is complete.
- [x] In the [WCAG2ICT FPWD](https://www.w3.org/TR/wcag2ict-22/) and editor's draft, should there be a "Latest Note:" that points to the 2013 finalized Note?  For example, in WCAG 2.2, there's a "Latest Recommendation" line that points to the 2.1 Recommendation.
- [x] The [W3C Technical Reports index](https://www.w3.org/TR/) no longer lists the 2013 version of the Note
- [x] The [WCAG2ICT Task Force page](https://www.w3.org/WAI/GL/task-forces/wcag2ict/) Announcements section: Link text reads "WCAG2ICT Draft for review" but points to the 2013 finalized version - Need to update the URL to be correct.
- [x] The [WCAG2ICT Work Statement page](https://www.w3.org/WAI/GL/task-forces/wcag2ict/work-statement) is also linking to the FPWD version rather than the 2013 version - update the URL.
- [x] Other standards that referenced the 2013 WCAG2ICT document are now instead pointing to the draft instead of the finalized, published document (e.g. Revised 508 standards, EN 301 549 and all other country-adopted versions of the EN 301 549). Notify those organizations that this has occurred, so they can update the link, if desired. (As of the 14 Aug. meeting, Bruce knows).

**Comment by daniel-montalvo** [comment]
Hi @maryjom  and all.

We are working with the Systems Team to fix these issues. WE will propose updates to all of the above soon.

**Comment by maryjom** [comment]
@daniel-montalvo There are two remaining issues in the list in this issue. I updated what I saw as the problem, as when the links changed, the issue changed a little bit with it. I checked off the ones that were fixed - thanks for that!

**Comment by daniel-montalvo** [comment]
> * [ ]  In the [WCAG2ICT FPWD](https://www.w3.org/TR/wcag2ict-22/) and editor's draft, should there be a "Latest Note:" that points to the 2013 finalized Note?  For example, in WCAG 2.2, there's a "Latest Recommendation" line that points to the 2.1 Recommendation.

Because WCAG2ICT is not technically a W3C Recommendation but a W3C Working Group Note, we had to remove that.
In the editor's draft we do have a previous version entry that points to the 2013 version. We could add this to https://www.w3.org/TR/wcag2ict-22/ next time we update the draft.

The Task Force Overview page is now updated.

**Comment by daniel-montalvo** [comment]
@maryjom  Can we close this?

The [Editor's Draft ](https://w3c.github.com/wcag2ict/.) now contains a "Previous version" link that points to the 2013 version.

This link will be included when we publish the updated working draft.
I think the other issues have been solved.

**Comment by maryjom** [comment]
Thanks @daniel-montalvo closing.
