### ISSUE TITLE
Change needed due to comment: Stale closed functionality examples

### ISSUE THREAD

**Issue by maryjom** [w3c/wcag2ict#217]
Excerpted from the public-comments-wcag2ict list's [thread](https://lists.w3.org/Archives/Public/public-wcag2ict-comments/2023Aug/thread.html): Specifically, the email [Re: Comments on WCAG2ICT Overview](https://lists.w3.org/Archives/Public/public-wcag2ict-comments/2023Aug/0003.html) from 24 August
Email thread and responses to general questions being tracked in Issue #215.

>I'm somewhat baffled by your examples of closed systems (reiterated from the 2013 doc).  I would have thought POS, POS terminals, Grocery SCOs and ATMs which comprise the vast majority of "closed systems" today would have been the more relevant examples for you to note (not ebooks, OS login screens or "travel kiosks").  For that matter, modern TVs these days.  No mention of mobile apps? There are many more menu boards than kiosks for that matter. Not sure what "travel kiosks" are specifically to be honest.

**Comment by maryjom** [comment]
@pday1 will make edits and the TF will resurvey. See the [survey results](https://www.w3.org/2002/09/wbs/55145/WCAG2ICT-closed-more-to-review/results) questions 4-6.

**Comment by pday1** [comment]
Modified content proposed in pull requests 
https://github.com/w3c/wcag2ict/pull/306 and https://github.com/w3c/wcag2ict/pull/307

**Comment by maryjom** [comment]
Pull requests were reviewed and approved by the TF on 1 Feb. Changes were merged into the branch where other Closed Functionality sections are being worked. Once the rest is agreed, all can be merged into main.

**Comment by maryjom** [comment]
Merged PR #254 into the editor's draft.
