### ISSUE TITLE
CSS pixels: How to measure CSS pixel equivalents for systems with closed functionality

### ISSUE THREAD

**Issue by melaniephilipp** [w3c/wcag2ict#227]
@melaniephilipp wrote on 2023-09-29:

> Do you have any guidance on how to measure the CSS pixel equivalents for <del>macOS software, Window software, or</del> systems with closed functionality for testing purposes?

Edit 2023-12-03: I am splitting this request into two parts. The present issue will address only closed functionality. Issue #200 will address macOS and Windows software. — @mitchellevan

**Comment by patrickhlauke** [comment]
The equivalent concept to the CSS pixel for macOS (and iOS/iPadOS) software development is the "point" (Apple's density independent pixel equivalent)

**Comment by melaniephilipp** [comment]
Right. I'm asking about how to measure the CSS pixel equivalents for macOS software, Window software, or systems with closed functionality for testing purposes.

**Comment by maryjom** [comment]
Thank you for taking the time to review the WCAG2ICT public draft. Our task force will review your comment and develop a response that we hope will address your concern. The response will be drafted in a comment on this issue, marked **DRAFT RESPONSE** until the Task Force reaches consensus.

**Comment by samogami** [comment]
This comment relates to [Issue #200](https://github.com/w3c/wcag2ict/issues/200)

**Comment by samogami** [comment]
The comment relates to [issue #200 ](https://github.com/w3c/wcag2ict/issues/200)

**Comment by mraccess77** [comment]
There are pixel rules apps for some platforms like Android and Windows that display a pixel rule as an overlay on top of the software being tested - this likely would only work for open software and not closed software.

**Comment by patrickhlauke** [comment]
However, you may not want a "pixel ruler", but an "Apple's `pt` ruler" or similar (yes, they'll often be the same in effect)

**Comment by samogami** [comment]
Not all non web software or closed systems have a css pixel equivalent. When an equivalent does not exist SC with css should not apply.

**Comment by Mstanic05** [comment]
Can you assign this to me!

**Comment by maryjom** [comment]
> Can you assign this to me!

Not if you are not in the WCAG2ICT Task Force.

**Comment by mitchellevan** [comment]
@Mstanic05, thanks for your earlier offer. We welcome any feedback that you might wish to contribute. However, @maryjom is correct that our Task Force will be responsible for answering the public comments on our FPWD (First Public Working Draft).

**Comment by mitchellevan** [comment]
I have split this request into two parts. The present issue will address only closed functionality. Issue #200 will address macOS and Windows software.

**Comment by mitchellevan** [comment]
@maryjom, as we discussed I've unassigned myself from this issue, so I can concentrate on other issues. In our weekly call we'll make sure to get it reassigned.

Following are my views.

@samogami wrote:
> Not all non web software or closed systems have a css pixel equivalent. When an equivalent does not exist SC with css should not apply.

The first sentence is certainly true. Regarding the second sentence, "not apply": This is not WCAG2ICT Task Force consensus. Rather, our draft [Applying "CSS pixel" to Non-Web Documents and Software](https://w3c.github.io/wcag2ict/#applying-css-pixel-to-non-web-documents-and-software) says the following, which I predict for closed functionality will be the more common of the two measures:

> When there is no platform-defined density-independent pixel measurement, the reference pixel size can be approximated ... Determine a viewing distance [and] Divide the viewing distance by 2688.

This is the same calculation as for CSS pixels in web content. A web page can render in browsers on with a wide variety of devices, with viewing distances and form factors ranging from wearables to smart TVs. So viewing distance calculations should yield results within similar ranges for closed functionality that they do for web content.

That said, the original question was not just about "how to calculate" but also "how to measure". On this I agree with Mary Jo's [comment in issue 200](https://github.com/w3c/wcag2ict/issues/200#issuecomment-1841304164):

> ... it isn't up to WCAG2ICT to define or list those tools. We could simply mention that some platforms have available measurement tools.

**Comment by mitchellevan** [comment]
DRAFT TASK FORCE REPLY:

Thank you for your question about how to measure a CSS pixel. As noted in my 2023-12-03 edit to the issue, we will address only closed functionality in the present issue. (For the other half of your question, see #200.)

There are two parts to this question.

#### Part 1: How can a person determine the meaning of "CSS pixel" on a given platform?
The WCAG2ICT update includes [Guidance When Applying “CSS pixel” to Non-Web Documents and Software](https://www.w3.org/TR/wcag2ict-22/#guidance-when-applying-css-pixel-to-non-web-documents-and-software). This guidance describes how the "CSS pixel" (as used in WCAG) can be approximated using one of two methods:

* Based on a platform-defined density-independent pixel, or
* Based on a viewing distance for a display type.

These two methods can be used for closed functionality software. Some closed functionality software runs on a platform that is open enough for the first method to be practical. Other closed functionality software runs on a specific hardware device, such as a self-service terminal or kiosk, where the physical screen size is known. Still other closed functionality software runs on a range of physical screens, such as smart TVs, where the software scales to fit the screen and thereby yields a predictable "CSS pixel" unit on any commonly-used physical screen.

#### Part 2: Using "CSS pixels" as the unit, how can a person measure parts of the user interface of closed functionality software?

If you use the platform-defined density-independent pixel method: Obtain a software tool that allows developers or testers to measure content in the density-independent pixel unit of the platform.

If you use the method of viewing distance for a display type: Project either the physical pixel size or the equivalent viewing angle onto a display of that type.

It is not feasible for this Task Force to list more specific measurement tools for these methods.

(END OF DRAFT REPLY)

**Comment by pday1** [comment]
Changes agreed from task force meeting today: 

Change penultimate paragraph: 
If you use the method of viewing distance: Calculate the reference pixel size as described in the Notes in the WCAG2ICT guidance for the definition of "CSS pixel".

Add sentence:
There may or may not be software tools available to measure.

**Comment by maryjom** [comment]
FINAL TASK FORCE REPLY:

Thank you for your question about how to measure a CSS pixel. As noted in my 2023-12-03 edit to the issue, we will address only closed functionality in the present issue. (For the other half of your question, see #200.) 

There are two parts to this question.

#### Part 1: How can a person determine the meaning of "CSS pixel" on a given platform?
The WCAG2ICT update includes [Guidance When Applying “CSS pixel” to Non-Web Documents and Software](https://www.w3.org/TR/wcag2ict-22/#guidance-when-applying-css-pixel-to-non-web-documents-and-software). This guidance describes how the "CSS pixel" (as used in WCAG) can be approximated using one of two methods:

* Based on a platform-defined density-independent pixel, or
* Based on a viewing distance for a display type.

These two methods can be used for closed functionality software. Some closed functionality software runs on a platform that is open enough for the first method to be practical. Other closed functionality software runs on a specific hardware device, such as a self-service terminal or kiosk, where the physical screen might be known.

#### Part 2: Using "CSS pixels" as the unit, how can a person measure parts of the user interface of closed functionality software?

If you use the platform-defined density-independent pixel method: Obtain a software tool that allows developers or testers to measure content in the density-independent pixel unit of the platform.

If you use the method of viewing distance: Calculate the reference pixel size as described in the Notes in the WCAG2ICT guidance for the definition of "CSS pixel".

It is not feasible for this Task Force to list more specific measurement tools for these methods. There may or may not be software tools available to measure. As a result, WCAG2ICT document will not be changed.

**Comment by maryjom** [comment]
Closing as answered.
