### ISSUE TITLE
Shortening "Guidance for..." section headings

### ISSUE THREAD

**Issue by maryjom** [w3c/wcag2ict#238]
The guidance headings in WCAG2ICT are too long and can be rephrased more succinctly. Note: If/when we change the headings, we've also got to update the in-document links to the sections, as the links also change due to the markdown. Will also need to modify the scripting that does numbers on notes and examples as it is keying off of the text "Guidance when Applying"

Suggest changing the heading:

>Guidance When Applying _**whatever it is**_ to Non-Web Documents and Software

to instead be something like this:

>Applying _**whatever it is**_ to Non-Web Documents and Software

Up for debate is whether we include the verbiage "Success Criterion", "Guideline", etc. in the heading. IMO, if we simply give the number or give the number and the name of the thing, it is pretty clear. Examples below are variations we could choose from:

------
For Principles:
### Applying 1 Perceivable Principle to Non-web Documents and Software

------
For Guidelines:
####  Applying 1.1 Text Alternatives Guideline to Non-web Documents and Software

------
For Success Criteria - note also the proposed addition of the SC short name in the heading per Issue #223 :
##### Applying 1.1.1 Non-text Contrast Success Criterion to Non-web Documents and Software

------
For term definitions:
#### Applying “accessibility supported” to Non-Web Documents and Software

**Comment by pday1** [comment]
Looks good to me. I personally find the first option in the list to be the least clumsy; namely
Applying 1.1.1 Non-text Contrast to Non-web Documents and Software

**Comment by olivia-hogan-stark** [comment]
+1 to Phil. I think the best choice is the first option, which excludes "Principle," "Guideline," and "Success Criteria." Reviewing the actual document and considering the other text and context surrounding these section headings, I find their inclusion repetitive and unnecessary.

**Comment by mapluke** [comment]
I am not very convinced of the need to shorten the titles. It is possible that those applying WCAG to software and documents may be less familiar with the layers of WCAG guidance, so seeing these listed in the titles may help to familiarize them with the important WCAG concepts.

**Comment by maryjom** [comment]
At the 12 October meeting we decided the following:
- For principles use: Applying Principle 1 Perceivable to Non-web Documents and Software
- For guidelines use: Applying Guideline 1.1 Text Alternatives to Non-web Documents and Software
- For Success Criteria use: Applying SC 1.1.1 Non-text Content to Non-web Documents and Software
- For definitions use: Applying “accessibility supported” to Non-Web Documents and Software

We'll have to make adjustments to the links and potentially also the scripting to ensure the document builds correctly.

**Comment by maryjom** [comment]
Closing this issue as it has been resolved.
