### ISSUE TITLE
Revisit Task Force decision on inclusion of WCAG Intent sections

### ISSUE THREAD

**Issue by maryjom** [w3c/wcag2ict#243]
For history, the WCAG2ICT TF made a decision on 27 April: [Include the WCAG SC Understanding Intent sections into document](https://www.w3.org/2023/04/27-wcag2ict-minutes#t06). The TF finds inclusion of this content helpful as we develop guidance to ensure it is aligned with the intent of WCAG. It also helps us identify problematic areas in the intent for which we open issues (in the WCAG repository) to fix and clarify in the intent.

Based on the [FPWD public comment on this inclusion](https://github.com/w3c/wcag2ict/issues/224), the task force would like to revisit whether or not to include the intent in the final document.  Two main concerns were stated in the FPWD issue: 
- Intent adds a lot of length to the document
- Intent content would become stale (outdated) over time

There are a few options for handling this in the final WCAG2ICT Note (maybe more):
- Do not include the intent, just have links to it
- Include the intent in a version of the document with collapsible sections
- Include the intent, and make WCAG2ICT guidance sections visibly different from the intent content (e.g. in its own callout box)

NOTE: If the intent is included, a script would be needed to dynamically pull in the current WCAG json Intent content upon use of the WCAG2ICT document link. This would ensure the Intent content doesn't get stale.

**Comment by mitchellevan** [comment]
+1 this:
> Include the intent in a version of the document with collapsible sections

I can also live with the other suggestions (linking; styling). It needs something for sure.

**Comment by maryjom** [comment]
An [AG WG comment(https://github.com/w3c/wcag2ict/issues/269#issuecomment-1850853443) from a review of new SC content in WCAG2ICT, indicates there are 4 people that think that a simple link and not including the Intent section's content is a good solution.

**Comment by bruce-usab** [comment]
I disagree that _linking_ to Intent has much utility.

> Intent content would become stale (outdated) over time.

I think this is actually a strength.  The "snapshot" helps explains reasoning for choices made in 2024 whereas more mature Intent (from updated Understanding) obscures the reasoning.  With the benefit of hindsight, I wish WCAG 2013 included more of this sort of background in the document itself.

**Comment by maryjom** [comment]
Included intent sections have been removed due to TF decision on 29 February. See PR #317 which has been merged into the document.
