### ISSUE TITLE
Success Criterion 2.4.11: Focus Not Obscured (Minimum) (Level AA)

### ISSUE THREAD

**Issue by samogami** [w3c/wcag2ict#249]
From [Success Criterion 2.4.11](https://www.w3.org/TR/WCAG22/#focus-not-obscured-minimum):

>When a [user interface component](https://www.w3.org/TR/WCAG22/#dfn-user-interface-components) receives keyboard focus, the component is not entirely hidden due to author-created content.
> Note 1: Where content in a configurable interface can be repositioned by the user, then only the initial positions of user-movable content are considered for testing and conformance of this Success Criterion.
> Note 2: Content opened by the user may obscure the component receiving focus. If the user can reveal the focused component without advancing the keyboard focus, the component with focus is not considered hidden due to author-created content.

##### Guidance When Applying Success Criterion 2.4.11 to Non-Web Documents and Software

- This applies directly as written, and as described in [Intent from Understanding Success Criterion 2.4.11](https://www.w3.org/WAI/WCAG22/Understanding/focus-not-obscured-minimum.html) (also provided below).

When a [user interface component](https://www.w3.org/WAI/WCAG22/Understanding/focus-not-obscured-minimum.html#dfn-user-interface-component) receives keyboard focus, the component is not entirely hidden due to author-created content.

> Where content in a configurable interface can be repositioned by the user, then only the initial positions of user-movable content are considered for testing and conformance of this Success Criterion.

> Content opened by the user may obscure the component receiving focus. If the user can reveal the focused component without advancing the keyboard focus, the component with focus is not considered hidden due to author-created content.

**Comment by maryjom** [comment]
Created draft PR and started a [survey on 2.4.11 proposal](https://www.w3.org/2002/09/wbs/55145/WCAG2ICT-focus-not-obscured/).

**Comment by maryjom** [comment]
This has been reviewed and approved by the AG WG. See Issue #267
