### ISSUE TITLE
WCAG2ICT Project: Add 1.3.5 Identify Input Purpose

### ISSUE THREAD

**Issue by maryjom** [w3c/wcag2ict#25]
- [x] Add [1.3.5 Identify Input Purpose](https://www.w3.org/WAI/standards-guidelines/wcag/new-in-21/#135-identify-input-purpose-aa) section (from WCAG 2.1)
- [x] Add in the [Understanding 1.3.5 Identify Input Purpose](https://www.w3.org/WAI/WCAG21/Understanding/identify-input-purpose.html) Intent and Benefits sections
- [x] Consider whether there are any notes needed for application of this SC to non-web technologies, and write them

**Comment by devchan4188** [comment]
See [Issue 66] for proposed content.

**Comment by maryjom** [comment]
Assigned to Chris to incorporate into the editor's draft.

**Comment by ChrisLoiselle** [comment]
@maryjom I created a draft in my branch, I'll share on our editorial call next week prior to Thursday's meeting with the larger group.

**Comment by maryjom** [comment]
@ChrisLoiselle I made a few code updates to the pull requests, marked my comments as resolved, and merged the changes. You can see the resulting content in the [1.3.5 Identify input purpose](https://w3c.github.io/wcag2ict/#identify-input-purpose) section of the editor's draft

**Comment by ChrisLoiselle** [comment]
@maryjom once AG WG reviews, is that when we close ? Thanks for clarifying.

**Comment by maryjom** [comment]
@ChrisLoiselle Yes. Once merged, I'm moving the issue to "Ready for AG WG review." Once reviewed/approved, we can close.

**Comment by maryjom** [comment]
AG WG has a [survey](https://www.w3.org/2002/09/wbs/55145/WCAG2ICT-First-AG-review-4-sc/) open until 9 March with AG WG survey results discussion at a TBD future date (after CSUN conference).

**Comment by maryjom** [comment]
On 21 March the AG WG approved SC 1.3.5 with changes that have since been merged.
