### ISSUE TITLE
AG WG Review: 2.4.11 Focus Not Obscured (Minimum) WCAG2ICT guidance

### ISSUE THREAD

**Issue by maryjom** [w3c/wcag2ict#267]
## Summary
Review of proposed WCAG2ICT guidance for 2.4.11 Focus Not Obscured (Minimum), as incorporated into the Editor's draft. This is new content in the Editor's draft.

## Maturity Level
Refining

## Action Needed
* Review content
* Use the thumbs up and thumbs down icons to indicate agreement or disagreement with various comments. Do not add comments to simply support other comments. 
* Note any suggested edits for improvement and/or reasoning either in a comment on this issue or by creating a PR on the WCAG2ICT document.  All SCs can be found in the [comments-by-guideline-and-success-criteria.md](https://github.com/w3c/wcag2ict/blob/main/comments-by-guideline-and-success-criterion.md) file.
----

## Content for Review

* Section [Applying SC 2.4.11 Focus Not Obscured (Minimum) to Non-Web Documents and Software](https://w3c.github.io/wcag2ict/#applying-success-criterion-2-4-11-focus-not-obscured-to-non-web-documents-and-software).

## Reference Material
In case you need them, links to various resources on 2.4.11

* [2.4.11 Focus Not Obscured (Minimum)](https://www.w3.org/TR/WCAG22/#focus-not-obscured-minimum) SC text in WCAG 2.2
* [Intent section of Understanding 2.4.11 Focus Not Obscured (Minimum)](https://www.w3.org/WAI/WCAG22/Understanding/focus-not-obscured-minimum#intent)

**Comment by mbgower** [comment]
Looks good. I agree there is no additional wording needed for WCAG2ICT.

**Comment by maryjom** [comment]
Closing this issue, as no substantive comments received and all reviews were a thumbs up.
