### ISSUE TITLE
AG WG Review: Term definition updates WCAG2ICT guidance changes

### ISSUE THREAD

**Issue by maryjom** [w3c/wcag2ict#270]
## Summary
There as some incorrect content in the 2013 WCAG2ICT for three glossary term definitions.

## Maturity Level
Refining

## Action Needed
* Review content
* Use the thumbs up and thumbs down icons to indicate agreement or disagreement with various comments. Do not add comments to simply support other comments. 
* Note any suggested edits for improvement and/or reasoning either in a comment on this issue or by creating a PR on the WCAG2ICT document.  All term definitions can be found in the [comments-on-definitions-in-wcag-2.2-glossary-in-appendix-a.md](https://github.com/w3c/wcag2ict/blob/main/comments-on-definitions-in-wcag-2.2-glossary-in-appendix-a.md) file.
----

## Content for Review

* Section [Applying "structure" to Non-Web Documents and Software](https://w3c.github.io/wcag2ict/#applying-structure-to-non-web-documents-and-software) was updated to remove extraneous content that didn't belong. See also [PR 233](https://github.com/w3c/wcag2ict/pull/233/files).
* Section [Applying "satisfies a success criterion" to Non-Web Documents and Software](https://w3c.github.io/wcag2ict/#applying-satisfies-a-success-criterion-to-non-web-documents-and-software). See also [PR 235](https://github.com/w3c/wcag2ict/pull/235/files).
* Moved "conformance" to the section [Glossary Items that Apply to All Technologies](https://w3c.github.io/wcag2ict/#glossary-items-that-apply-to-all-technologies). See also [PR 234](https://github.com/w3c/wcag2ict/pull/234/files).

## Reference Material
In case you need them, links to various resources on 3.3.7

* [structure](https://www.w3.org/TR/WCAG22/#dfn-structure) definition in WCAG 2.2
* [satisfies a success criterion](https://www.w3.org/TR/WCAG22/#dfn-satisfies) definition in WCAG 2.2
* [conformance](https://www.w3.org/TR/WCAG22/#def-conformance) definition in WCAG 2.2

**Comment by alastc** [comment]
I'm not familiar with the how linking works in the MD files, but I'll assume that's ok.

**Comment by maryjom** [comment]
Closing this issue, as no substantive comments received and all reviews were a thumbs up.
