### ISSUE TITLE
SC problematic for Closed functionality: SC 2.4.4 Link Purpose (In Context)

### ISSUE THREAD

**Issue by pday1** [w3c/wcag2ict#274]
From closed functionality questionnaire:
https://www.w3.org/2002/09/wbs/55145/wcag2ict-sc-problematic-for-closed/results#xq26

Mitchell Evan	|	Add 2.4.3 Link Purpose (In Context):
Requires text and context in a programmatically determinable form. Where another mechanism provides link purpose information for built-in assistive technology functions, this criterion does not apply.

**Comment by maryjom** [comment]
There was a typo in the proposal. Link Purpose is SC 2.4.4.  Mitch provided his proposal in the survey comment. Therefore, the choice is to either to not have a closed functionality bullet as it is today, or include a bullet the same as or similar to Mitch's proposed text. The survey will allow for alternate proposals.

**Proposal 1: Original**
No bullet for 2.4.3 Link Purpose (In Context).

**Proposal 2: Add bullet to SC problematic for closed functionality**
- 2.4.3 Link Purpose (In Context) - Requires text and context in a programmatically determinable form. Where another mechanism provides link purpose information for built-in assistive technology functions, this criterion does not apply.

**Comment by pday1** [comment]
For ease of review, here is content pulled from the latest Editor's draft to show the original "Applying SC to Non-Web..." alongside the proposed new content for "SC problematic for Closed...".

The latest editor's draft can be found at https://w3c.github.io/wcag2ict/
(Note this does not contain content that is in pull requests that are open and not yet approved)

**Content from Applying SC**
https://w3c.github.io/wcag2ict/#applying-sc-2-4-4-link-purpose-in-context-to-non-web-documents-and-software

> This applies directly as written and as described in [Intent from Understanding Success Criterion 2.4.4](https://www.w3.org/WAI/WCAG22/Understanding/link-purpose-in-context#intent) (also provided below).
> 
> NOTE
> In software, a “link” is any text string or image in the user interface outside a user interface control that behaves like a hypertext link. This does not include general user interface controls or buttons. (An OK button, for example, would not be a link.)


**Latest proposed content for SC problematic for Closed functionality section**

Proposal 1: Original
No bullet for 2.4.4 Link Purpose (In Context).

Proposal 2: Add bullet to SC problematic for closed functionality

2.4.4 Link Purpose (In Context) - Requires text and context in a programmatically determinable form. Where another mechanism provides link purpose information for built-in assistive technology functions, this criterion does not apply.

**Comment by maryjom** [comment]
Here's the [last survey results](https://www.w3.org/2002/09/wbs/55145/WCAG2ICT-closed-more-to-review/results#xq2) on the latest proposed content. Still looking to see if we had discussed the results of this survey in a meeting.

**Comment by pday1** [comment]
This issue has not been discussed in a meeting since the survey closed on 2024-01-10.
The survey had 3 saying accept as is, 3 with edits, but all edits were minor, so I think we can make the changes and then discuss a revised version.

**Comment by pday1** [comment]
For ease of review, here is content pulled from the latest Editor's draft to show the original "Applying SC to Non-Web..." alongside the proposed new content for "SC problematic for Closed...".

The latest editor's draft can be found at https://w3c.github.io/wcag2ict/
(Note this does not contain content that is in pull requests that are open and not yet approved)

**Content from Applying SC**
https://w3c.github.io/wcag2ict/#applying-sc-2-4-4-link-purpose-in-context-to-non-web-documents-and-software

> This applies directly as written and as described in [Intent from Understanding Success Criterion 2.4.4](https://www.w3.org/WAI/WCAG22/Understanding/link-purpose-in-context#intent) (also provided below).
> 
> NOTE
> In software, a “link” is any text string or image in the user interface outside a user interface control that behaves like a hypertext link. This does not include general user interface controls or buttons. (An OK button, for example, would not be a link.)

**Latest proposed content for SC problematic for Closed functionality section**

Proposal 1: Original

> No bullet for 2.4.4 Link Purpose (In Context).

Proposal 2 (proposed in survey): Add bullet to SC problematic for closed functionality

> 2.4.4 Link Purpose (In Context) - Requires text and context in a programmatically determinable form. Where another mechanism provides link purpose information for built-in assistive technology functions, this criterion does not apply.

**New proposal 3 - incorporating changes suggested in survey**

> 2.4.4 Link Purpose (In Context) - Requires text and context in a programmatically determinable form. Where another mechanism provides link purpose information for built-in assistive technology functions, the intent of this success criterion would be met.

**Comment by pday1** [comment]
@maryjom Now ready for discussion in the next TF meeting

**Comment by maryjom** [comment]
I've created the [survey](https://www.w3.org/2002/09/wbs/55145/WCAG2ICT-SC-problematic-remaining-sc/) which I'll open after the Friday, 8 March meeting.

**Comment by maryjom** [comment]
After the previous TF decision to move general "programmatic information" guidance into the introductory paragraph of the SC Problematic for Closed Functionality section, it was agreed the bullet for this SC would be a simple statement. In the extra Friday meeting on the 15 March meeting, we discussed Bruce's concerns regarding the use of "requires" in WCAG2ICT verbiage, which he is working on in Issue #328. So a new proposal that is aligned with his thinking is as follows:

- 2.4.4 Link Purpose (In Context) - This success criterion relies upon text and context made available in a programmatically determinable form.

**Comment by mapluke** [comment]
I like the option 2, but wondered if the following might be a little clearer:

- 2.4.4 Link Purpose (In Context) - This success criterion relies upon text and context **being** made available in a programmatically determinable form.

**Comment by maryjom** [comment]
TF agreed to changes on 11 April. See decision regarding SC Problematic for Closed: 2.4.4 Link Purpose (In Context) - [Incorporate Option 3, that has the small edit to add “being” as shown in the meeting minutes.](https://www.w3.org/2024/04/11-wcag2ict-minutes#r02)

Incorporated changes with PR #337.
