### ISSUE TITLE
SC problematic for Closed functionality: SC 1.3.1 Info and Relationships

### ISSUE THREAD

**Issue by pday1** [w3c/wcag2ict#275]
From closed functionality questionnaire:
https://www.w3.org/2002/09/wbs/55145/wcag2ict-sc-problematic-for-closed/results#xq25

Mitchell Evan	|	1.3.1 Info and Relationships: Make it like 4.1.2:
Requires information in a programmatically determinable form. Where another mechanism provides this information for built-in assistive technology functions, this criterion does not apply.

**Comment by maryjom** [comment]
We may be adjusting the language to 4.1.2 Name, Role, Value based on the [survey results on the review](https://www.w3.org/2002/09/wbs/55145/WCAG2ICT-SC-problematic-last-5/results#xq5). Once settled, use that language as a basis for this.

**Comment by pday1** [comment]
For ease of review, here is content pulled from the latest Editor's draft to show the original "Applying SC to Non-Web..." alongside the proposed new content for "SC problematic for Closed...".

The latest editor's draft can be found at https://w3c.github.io/wcag2ict/
(Note this does not contain content that is in pull requests that are open and not yet approved)

**Content from Applying SC**
https://w3c.github.io/wcag2ict/#applying-sc-1-3-1-info-and-relationships-to-non-web-documents-and-software

> This applies directly as written, and as described in [Intent from Understanding Success Criterion 1.3.1](https://www.w3.org/WAI/WCAG22/Understanding/info-and-relationships#intent) (also provided below).
> 
> NOTE 1
> In software, programmatic determinability is best achieved through the use of [accessibility services provided by platform software](https://w3c.github.io/wcag2ict/#accessibility-services-of-platform-software) to enable interoperability between software and assistive technologies and accessibility features of software.
> 
> NOTE 2
> See also the discussion on [Closed Functionality](https://w3c.github.io/wcag2ict/#closed-functionality).


**Latest proposed content for SC problematic for Closed functionality section**

> In draft

**Comment by maryjom** [comment]
Will work on this in the 8 March working session. Put a placeholder question in a [survey](https://www.w3.org/2002/09/wbs/55145/WCAG2ICT-SC-problematic-remaining-sc/) which I'll open after we develop content that aligns with the Name, Role, Value SC. Both will be worked on in the Friday, 8 March meeting.

**Comment by maryjom** [comment]
Taking into account that this SC requires Info and relationships to be either programmatically determined OR in text, a slight tweak to the 4.1.2 guidance we came up with in our 8 March meeting would be needed:

Existing content in editor's draft:
- [1.3.1 Info and Relationships](https://w3c.github.io/wcag2ict/#info-and-relationships) — Requires information in a programmatically determinable form.

Proposal: “help meet the intent”  

- [1.3.1 Info and Relationships](https://w3c.github.io/wcag2ict/#info-and-relationships)—Requires information in a programmatically determinable form or in text. Where this is not possible, providing equivalent information and operation through another mechanism, such as functions built into the software that behave like assistive technology, would help meet the intent of this success criterion.

**Comment by GreggVan** [comment]
I don’t think we should go beyond

"To the extent that this provision relies on 'programmatically determinable' -  see above discussion on problem with programmatically, determinable, provisions, and closed products.


Then, in one location  (above all the specific comments)    , we should talk about the fact that    
“programmatically determinable" means that it's accessible to T.. Close products by definition are not accessible to T.. Therefore some other mechanism for providing access that is equivalent to 80 is needed but beyond the scope of this document to propose.

**Comment by maryjom** [comment]
Consensus reached in the 14 March meeting. Do a slight update (noted in the [meeting minutes](https://www.w3.org/2024/03/14-wcag2ict-minutes#t06)) to the first sentence from the proposal so it reads:
>- [1.3.1 Info and Relationships](https://w3c.github.io/wcag2ict/#info-and-relationships)—Requires information in a programmatically determinable form or in text (that is programmatically determinable).

**Comment by maryjom** [comment]
The agreed content in PR #325 has been merged into the editor's draft. This can be closed.
