### ISSUE TITLE
SC problematic for Closed functionality: 4.1.3 Status Messages

### ISSUE THREAD

**Issue by pday1** [w3c/wcag2ict#277]
From closed functionality questionnaire:
https://www.w3.org/2002/09/wbs/55145/wcag2ict-sc-problematic-for-closed/results#xq25

Mitchell Evan	|	4.1.3 Status Messages: Keep the first two sentences. Change the "NOTE" to point to non-web software in general.

**Comment by pday1** [comment]
SC and Applying SC text reproduced below for reference: 

> 4.1.3 Status Messages
> 
> In content implemented using markup languages, status messages can be programmatically determined through role or properties such that they can be presented to the user by assistive technologies without receiving focus.


> Applying SC 4.1.3 Status Messages to Non-Web Documents and Software
> 
> This applies directly as written, and as described in [Intent from Understanding Success Criterion 4.1.3](https://www.w3.org/WAI/WCAG21/Understanding/status-messages.html#intent) (also provided below) replacing "In content implemented using markup languages" with "In content implemented using markup languages, or that supports status message notifications".
> 
> With this substitution, it would read: In [content implemented using markup languages, or that supports status message notifications], [status messages](https://www.w3.org/TR/WCAG22/#dfn-status-messages) can be [programmatically determined](https://w3c.github.io/wcag2ict/#dfn-programmatically-determined) through [role](https://w3c.github.io/wcag2ict/#dfn-role) or properties such that they can be presented to the user by [assistive technologies](https://w3c.github.io/wcag2ict/#dfn-assistive-technology) without receiving focus.
> 
> NOTE 1
> For [non-web documents](https://w3c.github.io/wcag2ict/#document) and [software](https://w3c.github.io/wcag2ict/#software) that are not implemented using markup languages, there is still a user need to have status messages be programmatically exposed so that they can be presented to the user by assistive technologies without receiving focus. This is typically enabled through the use of accessibility services of the user agent or platform software.
> 
> NOTE 2
> See also the discussion on [Closed Functionality](https://w3c.github.io/wcag2ict/#closed-functionality).

**Comment by maryjom** [comment]
I believe @mitchellevan's comment in the closed functionality survey was directed toward this content in the SC Problematic for Closed Functionality section:
>- [4.1.3 Status Messages](https://w3c.github.io/wcag2ict/#status-messages)—requires information in a programmatic determinable form. Additionally, software with closed functionality is not typically implemented using markup languages.
>
>NOTE 5
>Non-web software with closed functionality would need equivalent facilitation to provide access to status messages.

**Comment by maryjom** [comment]
As to @mitchellevan's comment. Changing the note to point back to the non-web software in general, in my mind, does not show what considerations there are for closed functionality where there is likely no OS or user agent support for status messages. So I don't think doing so is helpful in this case. 

For Closed functionality, there is no programmatic exposure of the status message and no operating system or user agent accessibility services for that support. Therefore, in such situations, status messages would have to be exposed to the user in a different, non-programmatic way that provides access to that information.

**Comment by bruce-usab** [comment]
I submit for the TF consideration that SC scoped to "content implemented using markup language" are categorically different from  SC which explicitly or implicitly require "programmed determined".

The following four SC include the caveat for "content implemented using markup language".  Taken literally, they are **not applicable** to non-web documents and non-web software.  If these SC are applicable, then by definition markup is available to the end user, and the WCAG SC applies as-is.
- [1.3.6 Identify Purpose](https://www.w3.org/TR/WCAG22/#identify-purpose) (Level AAA)
- [1.4.12 Text Spacing](https://www.w3.org/TR/WCAG22/#text-spacing)
- [4.1.1 Parsing](https://www.w3.org/TR/WCAG20/#ensure-compat-parses) (2.0 only)
- [4.1.3 Status Messages](https://www.w3.org/TR/WCAG22/#status-messages)

There are four SC which explicitly include "programmatically determined" without the "content implemented using markup language" constraint.  Those are:
- [1.3.1 Info and Relationships](https://www.w3.org/TR/WCAG22/#info-and-relationships)
- [2.4.4 Link Purpose](https://www.w3.org/TR/WCAG22/#link-purpose-in-context}
- [3.1.2 Language of Page](https://www.w3.org/TR/WCAG22/#language-of-page)
- [3.1.3 Language of Parts](https://www.w3.org/TR/WCAG22/#language-of-parts)

These four absolutely belong in the category of SC problematic for closed functionality.  SC which are problematic for closed functionality reflect accessibility barriers.  The SC are applicable to non-web documents and non-web software.  It falls to the non-web documents and non-web software to address those barriers.  WCAG2ICT can (and should) highlight those SC, but are applicable (after any needed word substitution).

**Comment by patrickhlauke** [comment]
> The following four SC include the caveat for "content implemented using markup language". Taken literally, they are not applicable to non-web documents and non-web software. If these SC are applicable, then by definition markup is available to the end user, and the WCAG SC applies as-is.
> 
> [1.3.6 Identify Purpose](https://www.w3.org/TR/WCAG22/#identify-purpose) (Level AAA)
> [1.4.12 Text Spacing](https://www.w3.org/TR/WCAG22/#text-spacing)
> [4.1.1 Parsing](https://www.w3.org/TR/WCAG20/#ensure-compat-parses) (2.0 only)
> [4.1.3 Status Messages](https://www.w3.org/TR/WCAG22/#status-messages)

i'd argue that at least for 1.3.6 and 4.1.3, the fact that they were written as "implemented using markup language" was not due to any peculiarity of markup languages themselves, but as a "convenient" way to exempt other technologies that may not have the ability to programmatically convey purpose/statuses. whereas once we move to non-web/native scenarios, technologies do exist that allow to satisfy the asks of the SCs - in the case of 4.1.3, specific notification type APIs that allow announcements to be sent directly to screen readers/AT (in a programmatic way that's actually much cleaner than the acrobatics web developers need to do with `aria-live` and similar).

this is different from 4.1.1 and 1.4.12's reason for being scoped to "implemented using markup languages", because there the actual requirement makes no sense, as written, in other scenarios ... for 1.3.12, unless something's marked up and then styled separately with something like css stylesheets, there's no way a user can try to influence the visual presentation. and for 4.1.1, unless something's marked up using markup languages, there's no way/point to check whether or not that markup is valid.

so there's nuance there that should be aknowledged. otherwise, we're letting off non-web applications that show notifications, status messages, etc and allow them NOT to announce them to AT, purely because the original SC was (wrongly, in my view) scoped to "in markup languages" in a mistaken attempt at somehow saying "using `aria-live` or similar" without being technology-specific)

**Comment by pday1** [comment]
For ease of review, here is content pulled from the latest Editor's draft to show the original "Applying SC to Non-Web..." alongside the proposed new content for "SC problematic for Closed...".

The latest editor's draft can be found at https://w3c.github.io/wcag2ict/
(Note this does not contain content that is in pull requests that are open and not yet approved)

**Content from Applying SC**
https://w3c.github.io/wcag2ict/#applying-sc-4-1-3-status-messages-to-non-web-documents-and-software

> This applies directly as written, and as described in [Intent from Understanding Success Criterion 4.1.3](https://www.w3.org/WAI/WCAG22/Understanding/status-messages.html#intent) (also provided below) replacing "In content implemented using markup languages" with "In content implemented using markup languages, or that supports status message notifications".
> 
> With this substitution, it would read: In [content implemented using markup languages, or that supports status message notifications], [status messages](https://www.w3.org/TR/WCAG22/#dfn-status-messages) can be [programmatically determined](https://w3c.github.io/wcag2ict/#dfn-programmatically-determined) through [role](https://w3c.github.io/wcag2ict/#dfn-role) or properties such that they can be presented to the user by [assistive technologies](https://w3c.github.io/wcag2ict/#dfn-assistive-technology) without receiving focus.
> 
> NOTE 1
> For [non-web documents](https://w3c.github.io/wcag2ict/#document) and [software](https://w3c.github.io/wcag2ict/#software) that are not implemented using markup languages, there is still a user need to have status messages be programmatically exposed so that they can be presented to the user by assistive technologies without receiving focus. This is typically enabled through the use of accessibility services of the user agent or platform software.
> 
> NOTE 2
> See also the discussion on [Closed Functionality](https://w3c.github.io/wcag2ict/#closed-functionality).

**Latest proposed content for SC problematic for Closed functionality section**

In draft - no content yet agreed

**Comment by patrickhlauke** [comment]
> With this substitution, it would read: In [content implemented using markup languages, or that supports status message notifications], [status messages](https://www.w3.org/TR/WCAG22/#dfn-status-messages) can be [programmatically determined](https://w3c.github.io/wcag2ict/#dfn-programmatically-determined) through [role](https://w3c.github.io/wcag2ict/#dfn-role) or properties such that they can be presented to the user by [assistive technologies](https://w3c.github.io/wcag2ict/#dfn-assistive-technology) without receiving focus.

Loving the first part, but wondering if the second part (about role and properties) may also need to be extended/tweaked in its interpretation, as in non-markup-language technologies that nonetheless support status message notifications, there may not even be a concept of "role" or even "programmatically-determined" ... success here would just be that ATs announce them

**Comment by mraccess77** [comment]
> > With this substitution, it would read: In [content implemented using markup languages, or that supports status message notifications], [status messages](https://www.w3.org/TR/WCAG22/#dfn-status-messages) can be [programmatically determined](https://w3c.github.io/wcag2ict/#dfn-programmatically-determined) through [role](https://w3c.github.io/wcag2ict/#dfn-role) or properties such that they can be presented to the user by [assistive technologies](https://w3c.github.io/wcag2ict/#dfn-assistive-technology) without receiving focus.
> 
> Loving the first part, but wondering if the second part (about role and properties) may also need to be extended/tweaked in its interpretation, as in non-markup-language technologies that nonetheless support status message notifications, there may not even be a concept of "role" or even "programmatically-determined" ... success here would just be that ATs announce them

I'm not sure it's just about announcement though as I could imagine assistive technology could do other things such as pop up an arrow for a low vision user to communicate that something had changed or even move the viewport if they elected for that.  Status messages also came up as things important for COGA.

**Comment by patrickhlauke** [comment]
> I'm not sure it's just about announcement though

sure, then something more general about it being exposed / available to AT. my point is that the idea of role or properties may not even be applicable (e.g. if an application directly interfaces with some underlying accessibility layer in the OS, or similar)

**Comment by maryjom** [comment]
We have to be careful not to reopen a debate on the main SC guidance which the TF reached consensus on almost a year ago in March 2023, and the AG WG approved in July 2023. That content was added in here for reference as we develop specific guidance and notes regarding closed functionality - where there is no AT and likely not any accessibility API to expose the programmatic message information.

**Comment by maryjom** [comment]
Original proposal for the SC problematic for closed functionality section was:
>4.1.3 Status Messages—Requires information in a programmatic determinable form. Additionally, software with closed functionality is not typically implemented using markup languages.
>
>NOTE: Non-web software with closed functionality would need equivalent facilitation to provide access to status messages.

New proposal based on input from the survey. 

>4.1.3 Status Messages—Requires information in a programmatic determinable form. Additionally, software with closed functionality is not typically implemented using markup languages.
>
>NOTE: Where another mechanism provides access to status messages, such as built-in assistive technology, would make it possible for the software to meet the intent of this success criterion.

**Comment by bruce-usab** [comment]
@patrickhlauke wrote:

> i'd argue that at least for 1.3.6 and 4.1.3, the fact that they were written as "implemented using markup language" was not due to any peculiarity of markup languages themselves, but as a "convenient" way to exempt other technologies that may not have the ability to programmatically convey purpose/statuses.

I do not disagree.  I will go further, as I think this accounts for 4.1.1 being written as it was.

> whereas once we move to non-web/native scenarios, technologies do exist that allow to satisfy the asks of the SCs...

I agree that the _intent_ of these SC are broadly applicable, but, for better or worse, that goes beyond the remit of WCAG2ICT.  I agree that it can (and should) be noted that APIs exist to achieve similar outcomes for non-web software  If the SC needs more than simple word substitution, then maybe the SC is not literally applicable?  Section 508 and EN 301 549 include accessibility requirements that go beyond WCAG.  The same regulations that make WCAG enforceable have can fill in gaps; it's not all up to WCAG2ICT.

> so there's nuance there that should be aknowledged. otherwise, we're letting off non-web applications

I agree on both points, but the TF is not chartered to re-write SC.

**Comment by GreggVan** [comment]
I concur with Bruce
and also highlight that the concern you have (which is legitimate Patrick) is already taken care of in both 508 and EN 301 549 by other provisions.   So it does not **have** to be covered (see BruceB)  by stretching 4.1.1 beyond markup languages.  So all is good.  we can't cover the issue for non-markup but don't need to.    Best

**Comment by maryjom** [comment]
Remember, this issue is not for a broader discussion of applicability of 4.1.3 Status Messages to all non-web software, but instead to develop specific thoughts on problems applying it to software of ICT with closed functionality.

**Comment by bruce-usab** [comment]
@maryjom et al., I took two fresh stabs at 4.1.3, in the Google Doc, which I presume is little better for conversation.
1. [taken literally](https://docs.google.com/document/d/1ejuKX3cq06b3MY48h2wJPHJXfFYJLIjI0rUNf3PfoJQ/edit#heading=h.h23pqwfqw5cj)
2. [go big](https://docs.google.com/document/d/1ejuKX3cq06b3MY48h2wJPHJXfFYJLIjI0rUNf3PfoJQ/edit#heading=h.z2ugc5o5w7os)

Somewhat to my surprise, from the perspective of ICT closed functionality, the notes are virtually identical.

**Comment by pday1** [comment]
Consensus from 22 Feb 2024. 

Option 1: 
Applying SC 4.1.3 Status Messages to Non-Web Documents and Software
This applies directly as written, and as described in Intent from Understanding Success Criterion 4.1.3 (also provided below) without word substitution.

**Comment by maryjom** [comment]
The changes have been incorporated using PR #314.

**Comment by maryjom** [comment]
This content in PR #314 has been merged into the editor's draft, so this can be closed.
