### ISSUE TITLE
SC problematic for Closed functionality: 1.4.11 Non-text Contrast

### ISSUE THREAD

**Issue by pday1** [w3c/wcag2ict#278]
From closed functionality questionnaire:
https://www.w3.org/2002/09/wbs/55145/wcag2ict-sc-problematic-for-closed/results#xq25

Mitchell Evan	|	1.4.11 Non-text Contrast
1. The nested <ul> needs to be inside a parent <li>.
2. Don't mention EN 301 549 here. As of version 3.2.1, it does not include a contrast requirement for hardware. (It is true that Section 508 includes a contrast requirement for hardware "icons" even though it does not include this WCAG 2.1 criterion for web and software.)

**Comment by maryjom** [comment]
I had previously handled these things in PR #222.

**Comment by ChrisLoiselle** [comment]
Unassigning myself due to this being closed.
