### ISSUE TITLE
Should Coga be reviewing this?

### ISSUE THREAD

**Issue by lseeman** [w3c/wcag2ict#279]
HI

Julie just brought a specific issue to coga this week.  I think COGA should actually do a full review of this document. At what point in the process would that be possible?

**Comment by maryjom** [comment]
@lseeman I can understand COGA's interest in WCAG2ICT.  It is important to note though:
- WCAG2ICT is completely non-normative
- It makes no new requirements and provides no techniques for meeting requirements.
- It simply provides interpretation of WCAG Success Criteria in non-web document and software contexts - mainly in the form of word substitutions of non-web language for web language. 

Not all of the content is in the document yet. The current [editor's draft](https://w3c.github.io/wcag2ict/) is fairly complete with all but two of the WCAG 2.2 Success Criteria added. We plan to publish again in early March 2024. The finalized Note is expected to publish around June 2024.

The AG WG is currently reviewing the latest 4 success criteria and 3 definitions (using [5 issues](https://github.com/w3c/wcag2ict/issues?q=is%3Aissue+is%3Aopen+label%3A%22Please+Review%22)) and we will discuss results on 12 December in the AG WG meeting. If COGA wishes to also review those, you are quite welcome to.

**Comment by julierawe** [comment]
Hi, circling back on this. COGA discussed this with Rachael, who said tomorrow's WCAG2ICT review is not the right forum to mention concerns about an existing success criterion that the ICT is expanding to cover non-web documents and software. COGA will take a closer look at the [Intent section of Understanding 3.3.7 Redundant Entry](https://www.w3.org/WAI/WCAG22/Understanding/redundant-entry.html#intent) and decide if we want to start a new GitHub issue asking for more clarity in that section, thanks.

**Comment by maryjom** [comment]
I will close this issue and @lseeman @julierawe you can open issues if COGA finds things for us to change or clarify in the WCAG2ICT guidance. Thanks for your interest.
