### ISSUE TITLE
WCAG2ICT Project: Add 1.4.12 Text Spacing

### ISSUE THREAD

**Issue by maryjom** [w3c/wcag2ict#28]
- [x] Add [1.4.12 Text Spacing](https://www.w3.org/WAI/standards-guidelines/wcag/new-in-21/#1412-text-spacing-aa) section (from WCAG 2.1)
- [ ] Add in the [Understanding 1.4.12 Text Spacing](https://www.w3.org/WAI/WCAG21/Understanding/text-spacing.html) Intent and Benefits sections
- [x] Consider and write up whether there are any notes needed for application of this SC to non-web technologies

**Comment by ferBonnin** [comment]
Issue #62 has proposed content

**Comment by maryjom** [comment]
@ferBonnin Thank you! Is it ready for Task Force discussion? If so, I'll add to this week's agenda.

**Comment by ferBonnin** [comment]
@maryjom yes, I think it is ready for discussion.

**Comment by maryjom** [comment]
This content had been approved by the TF and incorporated in PR #132. This content was approved by the AG WG on 11 April. Closing.
