### ISSUE TITLE
Note 8 in "Set of software programs" does not list all relevant criteria

### ISSUE THREAD

**Issue by mitchellevan** [w3c/wcag2ict#283]
Note 8 currently says:

> Although the term “software” is used throughout this document because this would apply to stand alone software programs as well as individual software components and the software components in software-hardware combinations, the concept of “set of software programs” would only apply (by definition) to programs that can be launched separately from each other. Therefore, for the provisions that use the phrase “set of” (success criteria 2.4.1, 2.4.5, 3.2.3, and 3.2.4), the phrase “set of software programs” is used.

The list needs to include a couple of other success criteria that mention "set of software". I think it's only these:
* 3.2.6 Consistent Help (Level A, new in WCAG 2.2)
* 2.4.8 Location (Level AAA, WCAG 2.0)

**Comment by maryjom** [comment]
@mitchellevan Good point!  Since adding WCAG 2.2 criteria, this list needs updating for sure.

**Comment by maryjom** [comment]
@mitchellevan We don't have guidance for Level AAA criteria in the document at this point, so do not think we need to list that in the "set of software" definition for the WCAG2ICT guidance quite yet.  I've created PR #290 to add 3.2.6 to the list though.

**Comment by maryjom** [comment]
@mitchellevan Please review the PR to make sure your comment was appropriately incorporated and I'll merge in the change.
