### ISSUE TITLE
Clarify software note for all SC that "interprets pointer actions" or add note that these SC apply to platform software and user agents

### ISSUE THREAD

**Issue by maryjom** [w3c/wcag2ict#284]
Feedback from the review of 2.5.7 Dragging Movements (in issue #268) indicates it wasn't clear that this SC applies to user agents and platform software. Current note states:
>This requirement applies to **[[software](https://w3c.github.io/wcag2ict/#software)]** that interprets pointer actions (i.e. this does not apply to actions that are required to operate the **[underlying platform software]** or assistive technology).

This same note is also used for 2.5.1 Pointer Gestures and 2.5.2 Pointer Cancellation so if/when it changes, it needs to change in all three places. 

The original WCAG note, before word substitutions was:
>This requirement applies to web content that interprets pointer actions (i.e. this does not apply to actions that are required to operate the user agent or assistive technology).

Perhaps we can instead say:
>This requirement applies to **[user agents and other [software applications](https://w3c.github.io/wcag2ict/#software) that interpret]** pointer actions (i.e. this does not apply to actions that are required to operate the **[underlying platform software]** or assistive technology).

and then add a note for operating systems (platform software).  
>This requirement also applies to **[platform software]** that interprets pointer actions. This does not apply to actions that are required to operate the assistive technology).

**Comment by alastc** [comment]
> This requirement also applies to [platform software] that interprets pointer actions (i.e. this does not apply to actions that are required to operate the assistive technology).

I'm not sure the "I.e." follows, as the actions are a sub-set of things you can do with a pointer. Should it be (for each):

This requirement also applies to [platform software] that interprets pointer actions. The requirement does not apply to actions that are required to operate the assistive technology.

**Comment by maryjom** [comment]
@alastc Yes, it could be said that way. I was just following the WCAG phrasing and verbiage with as little change as possible.

**Comment by GreggVan** [comment]
+1 to Alastair's version.  " i.e."  means "in other words"   so what follows i.e. must be the same as what precedes it.

Alastair's version avoids an error in the use if "i.e". 

In WCAG is it almost wrong  -- but sort of right -  in that  what precedes it says that it applies to web content and the i.e. talks about all the things that are not web content but below it.   So it is technically correct... barely.  sorta.  but bad form.  I would change it but too late now. 

so lets go with Alastair's  reword.

**Comment by maryjom** [comment]
@alastc @GreggVan I've updated the initial proposal to incorporate the change.

**Comment by maryjom** [comment]
This verbiage was approved in the 11 January 2024 meeting as a result of the [survey](https://www.w3.org/2002/09/wbs/55145/WCAG2ICT-public-comment-responses/results#xq6).  Also had Michael Gower, originator of the comment, review the proposed change.
