### ISSUE TITLE
WCAG2ICT Project: Add 1.4.13 Content on Hover or Focus

### ISSUE THREAD

**Issue by maryjom** [w3c/wcag2ict#29]
- [x] Add [1.4.13 Content on Hover or Focus](https://www.w3.org/WAI/standards-guidelines/wcag/new-in-21/#1413-content-on-hover-or-focus-aa) section (from WCAG 2.1)
- [ ] Add in the [Understanding 1.4.13 Content on Hover or Focus](https://www.w3.org/WAI/WCAG21/Understanding/content-on-hover-or-focus.html) Intent and Benefits sections
- [x] Consider and write up whether there are any notes needed for application of this SC to non-web technologies

**Comment by nitedog** [comment]
Added [SC 1.4.13 Content on Hover or Focus](https://github.com/w3c/wcag2ict/issues/108)

**Comment by maryjom** [comment]
The TF approved content for 1.4.13 was added using PR #119. The AG WG approved the content on 11 April.
