### ISSUE TITLE
Seeking official discussion of SC 1.4.10 Reflow on native mobile apps

### ISSUE THREAD

**Issue by mraccess77** [w3c/wcag2ict#3]
My initial feeling is that SC 1.4.10 reflow would be very difficult to measure on native mobile apps like iOS and Android that are not web-based.  Does this SC apply to native mobile apps?  If so -- without access to the code are there any suggestions for testing?

**Comment by maryjom** [comment]
Moved to WCAG2ICT repository as the new TF will work to address issues tagged as WCAG2ICT from the WCAG repository.

**Comment by maryjom** [comment]
WCAG2ICT TF discussion on application of 1.4.10 Reflow to non-web software and documents is happening in the WCAG2ICT Issue #98 where we are discussing and drafting guidance content. Join in there if you wish to weigh in. I know some of you already are.

**Comment by maryjom** [comment]
The TF has published [guidance for Applying 1.4.10 Reflow to non-web documents and software](https://www.w3.org/TR/wcag2ict/#guidance-when-applying-success-criterion-1-4-10-to-non-web-documents-and-software) in its FPWD. If you have questions or comments on this guidance, please open a new issue.
