### ISSUE TITLE
WCAG2ICT Project: Add 2.1.4 Character Key Shortcuts

### ISSUE THREAD

**Issue by maryjom** [w3c/wcag2ict#30]
- [x] Add [2.1.4 Character Key Shortcuts](https://www.w3.org/WAI/standards-guidelines/wcag/new-in-21/#214-character-key-shortcuts-a) section (from WCAG 2.1) (add to comments-by-guideline-and-success-criterion.md under the heading character-key-shortcuts)
- [ ] Add in the [Understanding 2.1.4 Character Key Shortcuts](https://www.w3.org/WAI/WCAG21/Understanding/character-key-shortcuts.html) Intent and Benefits sections
- [x] Consider and write up whether there are any notes needed for application of this SC to non-web technologies

**Comment by samogami** [comment]
See [issue 76](https://github.com/w3c/wcag2ict/issues/76) for proposed content.

**Comment by maryjom** [comment]
AG WG has a [survey](https://www.w3.org/2002/09/wbs/55145/WCAG2ICT-First-AG-review-4-sc/) open until 9 March with AG WG survey results discussion at a TBD future date (after CSUN conference).

**Comment by maryjom** [comment]
On 21 March, the AG WG approved this SC, with changes that have since been merged.
