### ISSUE TITLE
Use of requires or required or requiring

### ISSUE THREAD

**Issue by bruce-usab** [w3c/wcag2ict#329]
The document at present uses "requires" (et al.) literally correctly in all instances, but its clarity could be improved by a synonym in many places.  On the [call 3/14,](https://lists.w3.org/Archives/Public/public-wcag2ict-tf/2024Mar/0016.html) I volunteered to do an editorial pass to address this.  Gregg provided [a search (.docx)](https://lists.w3.org/Archives/Public/public-wcag2ict-tf/2024Mar/att-0016/Requires_-_search.docx)

My goal is only to have "requires" in cases...
- where the word requires is part of sentence closely paraphrasing an SC
- referencing normative requirements of WCAG 2

I will use different phrasing if "requires" is an observation or statement of truth.

For example, instead of something like:
> SC 9.8.7 requires that XYX be programmatically determinable

I might use:
> SC 9.8.7 relies upon XYX being programmatically determinable
 
Or:
> a precondition for evaluation of SC 9.8.7 is that XYX is programmatically determinable

**Comment by bruce-usab** [comment]
Will be closed by #328

**Comment by maryjom** [comment]
I personally like "relies upon". It's a succinct replacement for "requires".

**Comment by maryjom** [comment]
@bruce-usab How's the PR going?  I've added some comments to it, and a concern that this PR is less about the use of "requires" and more about general editorial updates. I'd prefer a more focused PR that could go to the TF to reach consensus on. Other editorial updates will be the next round of changes for the document once we have the language for these SC problematic for closed functionality more consistent.

**Comment by maryjom** [comment]
Trying out some options for changes suggested for the group to survey. Here's an example proposal for 4.1.3 Status Messages.

**Current text**
- Requires information in a programmatically determinable form. _Instead, a closed functionality software equivalent would be to provide a meaningful reading sequence through auditory output or some other non-visual means that helps users correlate the output with the corresponding information displayed on the screen._

NOTE: The second sentence (notated in italics above) is being removed, as similar language has been added to the introductory paragraph in the section to generically state this for all SC requiring programmatic info.

**Option 1:**
- 4.1.3 Status Messages - This success criterion relies upon status messages being programmatically determinable through [role](https://www.w3.org/TR/WCAG22/#dfn-role) or properties.

**Option 2:**
- 4.1.3 Status Messages - Relies upon status messages being programmatically determinable using [role](https://www.w3.org/TR/WCAG22/#dfn-role) or properties.

**Option 3: From the 15 March meeting**
- 4.1.3 Status Messages - Assumes the use of status messages in a programmatically determinable form.
