### ISSUE TITLE
WCAG2ICT Project: Add 2.5.3 Label in Name

### ISSUE THREAD

**Issue by maryjom** [w3c/wcag2ict#33]
- [x] Add [2.5.3 Label in Name](https://www.w3.org/WAI/standards-guidelines/wcag/new-in-21/#253-label-in-name-a) section (from WCAG 2.1)
- [x] Add in the [Understanding 2.5.3 Label in Name](https://www.w3.org/WAI/WCAG21/Understanding/label-in-name.html) Intent and Benefits sections
- [x] Consider and write up whether there are any notes needed for application of this SC to non-web technologies

**Comment by maryjom** [comment]
@anastasialanz Do you need any assistance in getting started on this proposal? If so, let me know.

**Comment by devchan4188** [comment]
Proposed content in issue #99

**Comment by maryjom** [comment]
This SC was approved by the AG WG on 11 April.
