### ISSUE TITLE
Project task: Update contributors and company affiliations

### ISSUE THREAD

**Issue by maryjom** [w3c/wcag2ict#331]
Before we publish the next public draft, we need to update the [Acknowledgements section](https://w3c.github.io/wcag2ict/#acknowledgements).

- [x] Ensure everyone's company affiliations are correct/updated
- [x] Update the contributors from the AG WG (look at all issues where AG WG did a review to check for people's names to add to the document.)
- [x] Ask AG WG to review and submit updates that we'll incorporate prior to publishing.

**Comment by ChrisLoiselle** [comment]
@maryjom 

Do you intend to survey this to see what the responses are within the group (AG and WCAG2ICT) ? 

If not, are we going to email the group(s) with the ask ?

I did not review minutes to see who had present +'d to showcase attendance within the WCAG2ICT calls.

Per my review of issues we are working on as well as email threads, I came up with the following people for a list.

1. Mike Gower
2. Dan Bjorge
3. JAWS-test (not sure who that is)
4. Patrick Lauke
5. Roberto Scano
6. Wilco Fiers
7. Jonathan Avila
8. Phil Day
9. Mitchell Evan
10. Sam Ogami
11. Olivia Hogan-Stark
12. Gregg Vanderheiden
13. FerBonnin ? Not sure who this is.
14. Laura Boniello Miller
15. Loïc Martínez Normand
16. Bruce Bailey
17. jamie herrera - Jamie H
18. Sarah Arnold
19. melanie philipp
20. Mstanic05 - not sure who this is
21. Lisa Seeman
22. Daniel Montalvo
23. Scott O'Hara
24. Detlev Fischer
25. Radhika Soni
26. chaals
27. Alastair Campbell
28. Alex Umstead
29. Glenda Sims
30. Peter Korn
31. Chris McMeeking
32. Joe Humbert
33. carrythebanner
34. Charles Adams (Chuck) 
35. Janina Sajka
36. Jason White
37. Matthew Atkinson
38. Michael Cooper
39. Shawn Thompson

Let me know if anything else is needed on this. I don't have all of these individuals emails, thus perhaps we ask them to email us ?

**Comment by maryjom** [comment]
Wow, thanks!  How’d you derive the list? Just curious…

We’ll need to see which persons in the list you have are not yet listed in one of the 3 sections of acknowledgements<https://w3c.github.io/wcag2ict/#acknowledgements> in our editor’s draft and create a PR to add them. We’ll only need to add folks listed as AG WG participants<https://www.w3.org/groups/wg/ag/>.

When the AG WG reviews the document, we can also ask for them to check the contributor list and if we’ve missed anyone to let us know and we’ll add them.

Best regards,

Mary Jo Mueller
IBM Accessibility Standards Program Manager


From: Chris Loiselle ***@***.***>
Date: Wednesday, April 17, 2024 at 8:52 AM
To: w3c/wcag2ict ***@***.***>
Cc: Mary Jo Mueller ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [w3c/wcag2ict] Project task: Update contributors and company affiliations (Issue #331)
@maryjom Do you intend to survey this to see what the responses are within the group (AG and WCAG2ICT) ? If not, are we going to email the group(s) with the ask ? I did not review minutes to see who had present +'d to showcase attendance within
ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
This message came from outside your organization.
<https://us-phishalarm-ewt.proofpoint.com/EWT/v1/AdhS1Rd-!9BFTkjxRuuUR3xUypIwDehsEZxkm_x4zk3uT_-KoXtquhu42BKNzX3jqE1FfnLjWG2OUNgn_iotxTSM0UBdXOJY0VDWjLy4$>
Report Suspicious <https://us-phishalarm-ewt.proofpoint.com/EWT/v1/AdhS1Rd-!9BFTkjxRuuUR3xUypIwDehsEZxkm_x4zk3uT_-KoXtquhu42BKNzX3jqE1FfnLjWG2OUNgn_iotxTSM0UBdXOJY0VDWjLy4$>


ZjQcmQRYFpfptBannerEnd

@maryjom<https://github.com/maryjom>

Do you intend to survey this to see what the responses are within the group (AG and WCAG2ICT) ?

If not, are we going to email the group(s) with the ask ?

I did not review minutes to see who had present +'d to showcase attendance within the WCAG2ICT calls.

Per my review of issues we are working on as well as email threads, I came up with the following people for a list.

  1.  Mike Gower
  2.  Dan Bjorge
  3.  JAWS-test (not sure who that is)
  4.  Patrick Lauke
  5.  Roberto Scano
  6.  Wilco Fiers
  7.  Jonathan Avila
  8.  Phil Day
  9.  Mitchell Evan
  10. Sam Ogami
  11. Olivia Hogan-Stark
  12. Gregg Vanderheiden
  13. FerBonnin ? Not sure who this is.
  14. Laura Boniello Miller
  15. Loïc Martínez Normand
  16. Bruce Bailey
  17. jamie herrera - Jamie H
  18. Sarah Arnold
  19. melanie philipp
  20. Mstanic05 - not sure who this is
  21. Lisa Seeman
  22. Daniel Montalvo
  23. Scott O'Hara
  24. Detlev Fischer
  25. Radhika Soni
  26. chaals
  27. Alastair Campbell
  28. Alex Umstead
  29. Glenda Sims
  30. Peter Korn
  31. Chris McMeeking
  32. Joe Humbert
  33. carrythebanner
  34. Charles Adams (Chuck)
  35. Janina Sajka
  36. Jason White
  37. Matthew Atkinson
  38. Michael Cooper
  39. Shawn Thompson

Let me know if anything else is needed on this. I don't have all of these individuals emails, thus perhaps we ask them to email us ?

**Comment by maryjom** [comment]
Hi Chris,

From this list, I don’t see the following in the current list of participants in the AG WG, so I don’t think we should list them:

  *   Chaals Nevile
  *   Rahika Soni
  *   Mstanic05 (don’t know who this is)
  *   Sarah Arnold
In addition, we should also add the following who participated in the most recent AG WG reviews of WCAG2ICT drafted content.

  *   Mike Gifford (Invited expert)
  *   Poornima Badhan Subramanian (Invited expert)
  *   Ben Tillyer (Invited expert)
  *   Julie Rawe (Understood)
Thinking we should also name Kevin White (W3C Staff) in the AG WG list, as he helped with the document to publish the FPWD. Perhaps also Shawn Henry (W3C Staff).
There are some WCAG2ICT participants who have not been actively participating, as they were alternate representatives. I’m not sure what the right course of action is for that situation. Will ask for Daniel’s guidance on that.
I also wonder what to do about people in the lists that are no longer AG WG participants. I’ll have to ask Daniel about that as well. Do we list them or not, and if we do, how should we indicate they were a former participant in the AG WG?
Best regards,

Mary Jo Mueller
IBM Accessibility Standards Program Manager


From: Chris Loiselle ***@***.***>
Date: Wednesday, April 17, 2024 at 9:53 AM
To: w3c/wcag2ict ***@***.***>
Cc: Mary Jo Mueller ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [w3c/wcag2ict] Project task: Update contributors and company affiliations (Issue #331)
@maryjom I reviewed the above mentioned list against what you mentioned in your reply. With my review of C1, C2 and C3 against AGWG Participants, I have the following that should be added to Participants list in WCAG2ICT Mike Gower Roberto
ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
This message came from outside your organization.
Report Suspicious <https://us-phishalarm-ewt.proofpoint.com/EWT/v1/AdhS1Rd-!9BFTkjxRuuUR3xUypIwDehsEZxkm_x4zk3uT_-KoXjrt2yV60ibKidtS0kVSbzDJlGVp47qBlr2BFs49KBoa5GMBKr2T0pI$>


ZjQcmQRYFpfptBannerEnd

@maryjom<https://github.com/maryjom> I reviewed the above mentioned list against what you mentioned in your reply. With my review of C1, C2 and C3 against AGWG Participants, I have the following that should be added to Participants list in WCAG2ICT

<mjm>I’ve adjusted this list below based on the changes in my email:

  1.  Michael Gower (IBM Corporation)
  2.  Roberto Scano (W3C Invited Expert)
  3.  Wilco Fiers (Deque Systems, Inc.)
  4.  Sarah Arnold
  5.  Melanie Phillip (Deque Systems, Inc.)
  6.  Mstanic05
  7.  Lisa Seeman-Kestenbaum (Invited Expert)
  8.  Scott O'Hara (Microsoft)
  9.  Rahika Soni
  10. Chaals
  11. Mike Gifford (Invited expert)
  12. Poornima Badhan Subramanian (Invited expert)
  13. Ben Tillyer (Invited expert)
  14. Julie Rawe (Understood)

Of the above, I'm not sure if Sarah Arnold , Mstanic05 (GitHub name) Rahika Soni and Chaals are currently associated with AGWG, as I search for their names on the participants W3C link, however they did not showcase GitHub or true name wise on that list.

The only item I did not review in full is what the "present plus" attendance lists showcase for "participating" names in our weekly calls. If Daniel or someone else could run a report to showcase the names in a numbered list or bulleted list, I can cross reference those against what I've gathered from email list correspondence, GitHub and known activity to date.

**Comment by daniel-montalvo** [comment]
> There are some WCAG2ICT participants who have not been actively participating, as they were alternate representatives. I’m not sure what the right course of action is for that situation.

I think we should still list them because they are actually participants. If we want to split these list to give more credits to those who actually contributed, we can split the list of TF participants into two:

* Active WCAG2ICT participants
* Other WCAG2ICT participants

> I also wonder what to do about people in the lists that are no longer AG WG participants. I’ll have to ask Daniel about that as well. Do we list them or not, and if we do, how should we indicate they were a former participant in the AG WG?

If we think it would be sensible to list some of these people I would add a "Former AGWG Participants" heading. Otherwise, I think it's fair to remove them since they are no longer participating in AGWG at the time of publication.

**Comment by ChrisLoiselle** [comment]
@maryjom @daniel-montalvo This issue shows as open, however https://github.com/w3c/wcag2ict/pull/346 shows as merged. Are we tracking any other edits on this issue in addition to the merged content already integrated?

**Comment by maryjom** [comment]
@ChrisLoiselle Yeah, [Daniel's comment](https://github.com/w3c/wcag2ict/issues/331#issuecomment-2075207272) said we should add all of the WCAG2ICT TF participants, including those that were the backups. That part hasn't been done. Plus when AG reviews I'll be asking if we missed anyone that should be listed as a contributor.

**Comment by ChrisLoiselle** [comment]
@daniel-montalvo @maryjom I'd need the list of backups to include, however had reformatted the wording of the heading levels per @daniel-montalvo 's request.

**Comment by maryjom** [comment]
@ChrisLoiselle There's only three:
- Kent Boucher (Oracle)
- Tony Holland (IBM, Corp.)
- Anastasia Lanz (Deque)

@daniel-montalvo What do we do with Michael Cooper's name in the Participants list? Do we still include him in the "Active in the Development of this Document" section? Do we leave his affiliation as W3C, or should it be "former W3C staff"?

**Comment by maryjom** [comment]
@ChrisLoiselle I've added in the names to your PR and reviewed/approved it. Will merge in a minute.

**Comment by maryjom** [comment]
Closing this issue as completed. The WCAG2ICT editor's draft is now out for an AG WG CfC to publish for wide review.
