### ISSUE TITLE
Project task: Remove "previous version" respec key

### ISSUE THREAD

**Issue by daniel-montalvo** [w3c/wcag2ict#362]

**Comment by daniel-montalvo** [comment]
@maryjom  I think it makes sense for us to remove the following once the Note is published and updated.
> Previous Version https://www.w3.org/TR/wcag2ict/

If you agree, let's keep this open. If you don't, then let's close.

**Comment by maryjom** [comment]
Hmm...so the plan is to not have any link anywhere that points to the 2013 version of WCAG2ICT? Will the 2013 version still be available as a reference?

**Comment by daniel-montalvo** [comment]
I don't feel strongly, that was just a suggestion.

In case we removed it, there will still be the link in the Introduction > Background section. 
<blockquote>
<p>This document is an update to a <abbr title="World Wide Web Consortium">W3C</abbr> <a href="https://www.w3.org/2005/10/Process-20051014/tr#WGNote">Working Group Note</a> to incorporate new guidelines, success criteria, and definitions added in WCAG 2.1 and 2.2. </p>
<p><a href="https://www.w3.org/TR/2013/NOTE-wcag2ict-20130905/">Guidance on Applying WCAG 2.0 to Non-Web Information and Communications Technologies (WCAG2ICT)</a>, approved in September 2013, described how WCAG 2.0 could be applied to non-web documents and software. WCAG2ICT was organized to mirror WCAG's sections: Perceivable, Operable, Understandable, and Robust.  WCAG2ICT clarified when and how WCAG success criteria should be applied to non-web documents and software.  Some were applicable without modification and some were applicable with edits and/or notes.  Glossary terms were also reviewed. Level AAA success criteria were not addressed in the 2013 WCAG2ICT Working Group Note. </p>
</blockquote>
