### ISSUE TITLE
AG WG Review: 4.1.1 Parsing WCAG2ICT guidance

### ISSUE THREAD

**Issue by maryjom** [w3c/wcag2ict#364]
## Summary
Review of proposed WCAG2ICT guidance for 4.1.1 Parsing, as incorporated into the Editor's draft. This is update to the content was previously reviewed by the AG WG in Nov-Dec. 2023 (in Issue #266). There were some concerns indicated in that review regarding the content relating to WCAG 2.0 and 2.1. The TF has updated that part of the guidance by using the [2013 WCAG2ICT document's guidance for 4.1.1 Parsing](https://www.w3.org/TR/wcag2ict/#ensure-compat-parses) and making some updates to the examples and notes.

## Maturity Level
Refining

## Action Needed
* Review content (See Content for Review section below for details.)
* Use the thumbs up and thumbs down icons to indicate agreement or disagreement with various comments. Do not add comments to simply support other comments. 
* Note any suggested edits for improvement and/or reasoning either in a comment on this issue or by creating a PR on the WCAG2ICT document.  All SCs can be found in the [comments-by-guideline-and-success-criteria.md](https://github.com/w3c/wcag2ict/blob/main/comments-by-guideline-and-success-criterion.md) file.
----

## Background information 

Once finalized, this new WCAG2ICT Note will replace the 2013 Note, and it covers all three WCAG versions (2.0, 2.1, or 2.2).  This is important as different jurisdictions are using different versions of WCAG for the accessibility of information and communication technology. Since the existence of 4.1.1 Parsing is different, depending on the WCAG version, there is guidance for WCAG 2.2 and different guidance for WCAG 2.0 and 2.1.  

## Content for Review

* Section [Applying SC 4.1.1 Parsing to Non-Web Documents and Software](https://w3c.github.io/wcag2ict/#parsing).

## Reference Material
In case you need them, links to various resources on 4.1.1 Parsing

* WCAG 2.0 and 2.1 errata for Parsing can be found in the [WCAG 2.0 editorial errata #13](https://www.w3.org/WAI/WCAG20/errata/#editorial) and the [WCAG 2.1 editorial errata - last bullet](https://www.w3.org/WAI/WCAG21/errata/#editorial)
* [WCAG 2.2 4.1.1 Parsing](https://www.w3.org/TR/WCAG22/#parsing)

**Comment by mraccess77** [comment]
The original SC mentions markup languages and the note references markdown languages.

**Comment by alastc** [comment]
The " (per the WCAG errata.)" part of Note 4 is a bit confusing. If the editors note at the top is removed before publication, there will be no other mention of it.  Also, I think it's a note rather than errata.

I suggest linking through to the Note for each, e.g. (as outlined in the [WCAG 2.1 note on 4.1.1](https://www.w3.org/TR/WCAG21/#h-note-27))

**Comment by mraccess77** [comment]
> The original SC mentions markup languages and the note references markdown languages.

The note I was referring to above looks like it was updated to markup.  My comment was NOT about the area mentioning laText but in the note.  So it seems like this issue has already been addressed.

**Comment by maryjom** [comment]
See PR #379 to address comment from @alastc.
