### ISSUE TITLE
[Editorial] Take a pass for Oxford comma and decide whether or not to use

### ISSUE THREAD

**Issue by daniel-montalvo** [w3c/wcag2ict#365]

**Comment by maryjom** [comment]
@daniel-montalvo Chris already did a pass on oxford commas. We're using them and made some changes to the document to fix where they weren't used. If you notice any, feel free to create a PR.

**Comment by maryjom** [comment]
@daniel-montalvo There is an oxford comma missing in the W3C-added content to the Status of This Document section. Not sure if W3C style requires oxford commas or not but I was assuming it does. The text in question is:

>This is a draft document and may be updated, replaced or obsoleted by other documents at any time. It is inappropriate to cite this document as other than work in progress.

If oxford commas are used, there should be a comma after the word "replaced".

**Comment by daniel-montalvo** [comment]
Good catch, @maryjom  WAI style does require it but it seems W3C style does not.

**Comment by daniel-montalvo** [comment]
Closing. All our content uses Oxford commas, I'll thinkg about adding an open issue to W3C
 style.
