### ISSUE TITLE
AG WG Review: WCAG2ICT Guidance for Products with Closed Functionality

### ISSUE THREAD

**Issue by maryjom** [w3c/wcag2ict#370]
## Summary
The Task Force has updated and refreshed all of the guidance regarding products with closed functionality with more details about applying WCAG to non-web software where the system is closed to assistive technology or has more limited platform capabilities. We have defined two new key terms, updated the general guidance on closed functionality, as well as updated the section SC Problematic for Closed Functionality. All of the success criteria in WCAG 2.2 were analyzed to produce this content.

## Maturity Level
Refining

## Action Needed
* Review content (See Content for Review section below for details.)
* Use the thumbs up and thumbs down icons to indicate agreement or disagreement with various comments. Do not add comments to simply support other comments. 
* Note any suggested edits for improvement and/or reasoning either in a comment on this issue or by creating a PR on the WCAG2ICT document.  
    * The Key terms "closed functionality" and "menu-driven interface" are found in the file: [key-terms.md](https://github.com/w3c/wcag2ict/blob/main/key-terms.md)
    * Comments on Closed Functionality is found in the file: [closed-functionality.md](https://github.com/w3c/wcag2ict/blob/main/closed-functionality.md)
    * Success Criteria Problematic for Closed Functionality is found in the file: [success-criteria-problematic-for-closed-functionality.md](https://github.com/w3c/wcag2ict/blob/main/success-criteria-problematic-for-closed-functionality.md)
----

## Background information 

Once finalized, this new WCAG2ICT Note will replace the 2013 Note, and it covers all three WCAG versions (2.0, 2.1, or 2.2).  This is important as different jurisdictions are using different versions of WCAG for the accessibility of information and communication technology. 

## Content for Review

* Definition of [closed functionality](https://w3c.github.io/wcag2ict/#closed-functionality).
* Definition of [menu-driven interface](https://w3c.github.io/wcag2ict/#menu-driven-interface)
* [Comments on Closed Functionality](https://w3c.github.io/wcag2ict/#comments-on-closed-functionality)
* [Success Criteria Problematic for Closed Functionality](https://w3c.github.io/wcag2ict/#success-criteria-problematic-for-closed-functionality)

## Reference Material
None

**Comment by detlevhfischer** [comment]
@maryjom Under "action needed", it would help to include a link to the content to be reviewed.

**Comment by maryjom** [comment]
> @maryjom Under "action needed", it would help to include a link to the content to be reviewed.

I am following the AG WG template which has the links to the content to be reviewed listed under the "Content for Review" part (2 sections below "action needed").

**Comment by alastc** [comment]
Question that I'm not sure about regarding menu-driven interfaces: Does / should that include voice input? E.g. a telephone menu over audio where you say "two" instead of pressing the button.

**Comment by maryjom** [comment]
> Question that I'm not sure about regarding menu-driven interfaces: Does / should that include voice input? E.g. a telephone menu over audio where you say "two" instead of pressing the button.

I guess it could potentially include Interactive Voice Response (IVR) systems. However, the only place WCAG2ICT uses the term is with regard to 2.4.2 Page Titled - to indicate that if the ICT has a menu-driven interface there is no need for a page title.

**Comment by maryjom** [comment]
Closing this issue, since the AG WG review is done. WCAG2ICT document is now in CfC to publish that ends on 1 July.
