### ISSUE TITLE
AG WG Review: WCAG2ICT editor's draft

### ISSUE THREAD

**Issue by maryjom** [w3c/wcag2ict#372]
Please review the following major changes to the WCAG2ICT editor's draft. If you have comments or concerns with those sections, please add them in the specific issue for that topic:

- [Review: 3.2.6 Consistent Help WCAG2ICT guidance](https://github.com/w3c/wcag2ict/issues/369)
- [Review: 3.3.8 Accessible Authentication (Minimum) WCAG2ICT guidance](https://github.com/w3c/wcag2ict/issues/368)
- [Review: 4.1.1 Parsing WCAG2ICT guidance](https://github.com/w3c/wcag2ict/issues/364)
- [Review: WCAG2ICT Guidance for Products with Closed Functionality](https://github.com/w3c/wcag2ict/issues/370)

Now that the [WCAG2ICT document](https://w3c.github.io/wcag2ict/) is complete, please let us know if you see anything else of concern. If you find anything, add it in a comment on this issue.

**Comment by detlevhfischer** [comment]
> Now that the WCAG2ICT document is complete

@maryjom Where exactly is that complete document? (II may have bookmarked it at some point, but it would be helpful to have it directly referenced.

**Comment by maryjom** [comment]
Closing this issue, since the AG WG review is done. WCAG2ICT document is now in CfC to publish that ends on 1 July.
