### ISSUE TITLE
WCAG2ICT Project: Add from WCAG 2.2 - 2.4.11 Focus Not Obscured (Minimum)

### ISSUE THREAD

**Issue by maryjom** [w3c/wcag2ict#38]
- [x] Add [2.4.11 Focus Not Obscured (Minimum)](https://www.w3.org/TR/WCAG22/#focus-not-obscured-minimum) section (from WCAG 2.2)
- [x] Add in the [Understanding 2.4.11 Focus Not Obscured (Minimum)](https://www.w3.org/WAI/WCAG22/Understanding/focus-not-obscured-minimum.html) Intent and Benefits sections
- [x] Consider and write up whether there are any notes needed for application of this SC to non-web technologies

**Comment by samogami** [comment]
See issue #[249](https://github.com/w3c/wcag2ict/issues/249)

**Comment by maryjom** [comment]
This SC guidance has been incorporated into the document and approved by the AG WG review (see Issue #267). No comments were received on that review.
