### ISSUE TITLE
The word "[New]" is confusing

### ISSUE THREAD

**Issue by mitchellevan** [w3c/wcag2ict#387]
### Currently

The word "[New]" appears on six success criteria and two definitions. It appears to be pulled in automatically from WCAG. This is confusing because it only appears on the content that was new in WCAG 2.2. From a WCAG2ICT perspective, criteria and definitions added in WCAG 2.1 are also new, but they are not marked "[New]".

Example:

!['New' appears on 2.5.7 Dragging Movements but not on 2.5.4 Motion Actuation](https://github.com/w3c/wcag2ict/assets/3124805/15483e68-abfb-4e64-9ec7-8d4b763c1ccf)

https://w3c.github.io/wcag2ict/

### Proposed

Either remove the word "[New]" where it is currently appearing on WCAG 2.2 content, or add the word "[New]" on the content that was new in WCAG 2.1.

**Comment by maryjom** [comment]
That may have to be taken care of in the post-processing of the included text from WCAG. That text is a part of the include file from the WCAG 2.2 quoted text and not added by our document content directly.  @daniel-montalvo can this be removed via the scripting used when building the doc?
