### ISSUE TITLE
Platform software definition

### ISSUE THREAD

**Issue by rscano** [w3c/wcag2ict#395]
Definition inside document:

>  platform software 
>  software that runs on an underlying software or hardware layer and that provides a set of software services to other software components 
> 
>  NOTE 1 
>  Platform software may run or host other software, and may isolate them from underlying software or hardware layers. 
> 
>  NOTE 2 
>  A single software component may have both platform and non-platform aspects. 
> 
>  Example:  Examples of platforms are: desktop operating systems; embedded operating systems, including mobile systems; Web browsers; plug-ins to Web browsers that render a particular media or format; and sets of components that allow other applications to execute, such as applications which support macros or scripting. 
> 

Inside EN 301 549 is set as:

> **platform software (platform)**: collection of software components that runs on an underlying software or hardware layer, and that provides a set of software services to other software components that allows those applications to be isolated from the underlying software or hardware layer (after ISO/IEC 13066-1 [i.19])
> 
> NOTE: A particular software component might play the role of a platform in some situations and a client in others.
> 
> [i.19] ISO/IEC 13066-1:2011: "Information technology - Interoperability with assistive technology (AT) - Part 1: Requirements and recommendations for interoperability".

Suggestion: why don't use the EN definition and/or the ISO definition (adding also iso in D.1 informative references?

**Comment by maryjom** [comment]
The task force developed this definition as a combination of two different ISO definitions of platform software:
- ISO 9241-171:2008 [Ergonomics of human-system interaction Part 171: Guidance on software accessibility](https://www.iso.org/standard/39080.html). International Standards Organization. URL: https://www.iso.org/standard/39080.html
- ISO/IEC 13066-1:2011: [Information technology - Interoperability with assistive technology (AT) Part 1: Requirements and recommendations for interoperability](https://www.iso.org/standard/53770.html). International Standards Organization. URL: https://www.iso.org/standard/53770.html

When the WCAG2ICT Task Force worked on this, we took into account the definitions found in the EN 301 549 (Which used ISO 9241-171 and removed the examples) and the U.S. Revised 508 standards (which used a little from both of the above ISO standards, and included the examples) and the 4 different ISO definitions for "platform software".  We felt that the combination of the two listed above provided the necessary information and examples appropriate for the document.

Our Task Force has participants both the ETSI committee that developed the EN 301 549 and from the U.S. Access Board that developed the Revised 508 Standards.  We had a [meeting discussion](https://www.w3.org/2024/06/13-wcag2ict-minutes.html#t05) and made a [TF Resolution on 13 June](https://www.w3.org/2024/06/13-wcag2ict-minutes.html#r03) to use the definition as shown in [PR 378 changes to the Key Terms section](https://github.com/w3c/wcag2ict/pull/378/files#diff-9ce8dc60ecf3a9e0fb9483e1c0e5b0e1be662ff8a56a0e2f7c6ec418d01a9a35) starting on line 111.

The addition of the two ISO references is tracked in Issue #390, and will be done after this public draft is made available for review.

**Comment by maryjom** [comment]
Closing as completed, with the changes incorporated into the editor's draft.
