### ISSUE TITLE
 virtual keyboard (as used in WCAG2ICT) - change out the word "like"

### ISSUE THREAD

**Issue by ljoakley** [w3c/wcag2ict#396]
"virtual keyboard (as used in WCAG2ICT)
 any software that acts as a keyboard and generates output that is treated by other software like keystrokes from a keyboard". I would change the word "like" to more definite wording such as replacing it with "as" or "as if"

**Comment by GreggVan** [comment]
I  think changing it to “as”   is editorial and is fine.  

Gregg

**Comment by maryjom** [comment]
Thank you for your comment. This issue has been fixed in the latest Editor's draft using PR #396.
