### ISSUE TITLE
Inconsistent "used" vs. "required" in principles and guidelines (editorial)

### ISSUE THREAD

**Issue by mitchellevan** [w3c/wcag2ict#405]
### Currently

The first few principles and guidelines say something like this:

> In WCAG 2, the Guidelines are provided for framing and understanding the success criteria under them but are not **used** for conformance to WCAG. Guideline 2.2 applies directly as written.

However, starting with Guideline 2.3, the rest of the principles and guidelines say something like this:

> In WCAG 2, the Guidelines are provided for framing and understanding the success criteria under them but are not **required** for conformance to WCAG. Guideline 2.3 applies directly as written.

(Emphasis mine)

### Proposed

Change "required" to "used" for these.

**Comment by maryjom** [comment]
@mitchellevan Nice catch. This is another artifact from the 2013 document and is a good editorial change to make. As an FYI, since we are working to publish on Tuesday 2 July, I don't think we'll put any of these editorial changes into the document until after that date.

**Comment by maryjom** [comment]
This is language that originated in the 2013 WCAG2ICT and was not changed or updated in this version of the note. Is it really necessary to change the language? As an example, see [2013 WCAG2ICT guidance for Guideline 1.1 Text Alternatives](https://www.w3.org/TR/wcag2ict/#text-equiv).
