### ISSUE TITLE
WCAG2ICT Project: Add from WCAG 2.2 - 3.2.6 Consistent Help

### ISSUE THREAD

**Issue by maryjom** [w3c/wcag2ict#41]
- [x] Add [3.2.6 Consistent Help](https://www.w3.org/TR/WCAG22/#consistent-help) section (from WCAG 2.2)
- [x] Add in the [Understanding 3.2.6 Consistent Help](https://www.w3.org/WAI/WCAG22/Understanding/consistent-help.html) Intent and Benefits sections
- [x] Consider and write up whether there are any notes needed for application of this SC to non-web technologies

**Comment by olivia-hogan-stark** [comment]
**IN PROGRESS**

From [3.2.6 Consistent Help](https://www.w3.org/TR/WCAG22/#consistent-help):

If a [Web page](https://www.w3.org/TR/WCAG22/#dfn-web-page-s) contains any of the following help [mechanisms](https://www.w3.org/TR/WCAG22/#dfn-mechanism), and those mechanisms are repeated on multiple Web pages within a [set of Web pages](https://www.w3.org/TR/WCAG22/#dfn-set-of-web-pages), they occur in the same order relative to other page content, unless a change is initiated by the user:

- Human contact details;
- Human contact mechanism;
- Self-help option;
- A fully automated contact mechanism

Help mechanisms may be provided directly on the page, or may be provided via a direct link to a different page containing the information.

For this Success Criterion, "the same order relative to other page content" can be thought of as how the content is ordered when the page is serialized. The visual position of a help mechanism is likely to be consistent across pages for the same page variation (e.g., CSS break-point). The user can initiate a change, such as changing the page's zoom or orientation, which may trigger a different page variation. This criterion is concerned with relative order across pages displayed in the same page variation (e.g., same zoom level and orientation).

Additional Guidance When Applying Success Criterion 3.2.6 Consistent Help:
This applies directly as written and as described in [Intent from Understanding Success Criterion 3.2.6](https://www.w3.org/WAI/WCAG22/Understanding/consistent-help.html) (also provided below), replacing "" with "”

If a **[Web page](https://www.w3.org/TR/WCAG22/#dfn-web-page-s)** contains any of the following help [mechanisms](https://www.w3.org/TR/WCAG22/#dfn-mechanism), and those mechanisms are repeated on multiple **Web pages** within a **[set of Web pages](https://www.w3.org/TR/WCAG22/#dfn-set-of-web-pages)**, they occur in the same order relative to other **page content**, unless a change is initiated by the user:

- Human contact details;
- Human contact mechanism;
- Self-help option;
- A fully automated contact mechanism

Help mechanisms may be provided directly on the **page**, or may be provided via a direct link to a different **page** containing the information.

For this Success Criterion, "the same order relative to other **page content**" can be thought of as how the **content** is ordered when the **page** is serialized. The visual position of a help mechanism is likely to be consistent across **pages** for the same **page** variation (e.g., CSS break-point). The user can initiate a change, such as changing the **page's** zoom or orientation, which may trigger a different **page** variation. This criterion is concerned with relative order across **pages** displayed in the same **page** variation (e.g., same zoom level and orientation).

**Comment by olivia-hogan-stark** [comment]
Does "content" and "link" language need to be updated in Additional Guidance? Did I overdo any language swaps?

**Comment by maryjom** [comment]
@olivia-hogan-stark I took the liberty of editing your proposed text to add bolded text and brackets to highlight the word substitutions which makes it easier to review as well as convert into the markdown version to include in the document. I only wonder about the substitutions where "page variation" to was changed to "non-web document variation" or "non-web software variation". To me those are layout variations, like the adjustments made to web pages when you view on a mobile device or change the browser window size. If non-web documents and software have that notion, I was thinking we call it a "content layout variation".  What do you think?  Maybe we can take that to a broader TF discussion on this SC. 

One other thing is that "page content" could be simplified to "content" without adding in "non-web document" or "non-web software" in the first paragraph and again in Note 2. Again, that is debatable. Thinking I'll simply open a survey on this and get TF feedback. I'll start out the comments by making those observations and as others complete the survey they can weigh in.

**Comment by maryjom** [comment]
This is undergoing AG WG review until 28 May. Closing this issue, as any changes will be tracked using the AG WG issue #369 or any new issues that get opened.
