### ISSUE TITLE
Issues with the 'platform software' notes for 2.5.1, 2.5.2, 2.5.7

### ISSUE THREAD

**Issue by mitchellevan** [w3c/wcag2ict#414]
### Currently

Three SCs have this note in WCAG:

> This requirement applies to web content that interprets pointer actions (i.e. this does not apply to actions that are required to operate the user agent or assistive technology).

The three SCs are:
* 2.5.1 Pointer Gestures
* 2.5.2 Pointer Cancellation
* 2.5.7 Dragging Movements

WCAG2ICT should and does apply these three SCs to the platform software itself, e.g. a browser. However, the Notes as currently written are confusing about how the three SCs apply to platform software.

Example from current WCAG2ICT content for 2.5.2, quoting just the parts relevant to platform software:

<blockquote>

This applies directly as written,... making changes to the notes... for non-web software applications by replacing "web content that interprets" with "user agents and other software applications that interpret" and "user agent" with "underlying platform software", and for non-web platform software by replacing "web content" with "platform software".

With these substitutions, the notes would read:

(for non-web software)

Note 5
This requirement applies to [user agents and other [software](https://www.w3.org/TR/wcag2ict-22/#software) applications that interpret] pointer actions (i.e. this does not apply to actions that are required to operate the [underlying [platform software](https://www.w3.org/TR/wcag2ict-22/#platform-software)] or assistive technology).

Note 6
This requirement also applies to [platform software] that interprets pointer actions (i.e. this does not apply to actions that are required to operate the assistive technology).
</blockquote>

Issues:

* The "user agents" mentioned in Note 5 are one kind of platform software. To this extent Notes 5 and 6 are redundant.
* The "platform software" in Note 6 can also have further underlying platform software, but Note 6 does not mention this.
* (minor issue) Note 6 has these further edits not mentioned in the list of word substitutions: added "also"; removed "user agent or".

### Proposed

Use Note 5 only for applications that are not platform software.

Use Note 6 for all kinds of platform software. Don't attempt word substitution; this is now just an additional Note.

<blockquote>

(for non-web software)

Note 5
This requirement applies to [[software](https://www.w3.org/TR/wcag2ict-22/#software) applications that interpret] pointer actions (i.e. this does not apply to actions that are required to operate the [underlying [platform software](https://www.w3.org/TR/wcag2ict-22/#platform-software)] or assistive technology).

Note 6
This success criterion also applies to platform software, such as user agents, assistive technology software, and operating systems. Each layer is responsible for its own pointer actions only, not for those in an underlying layer.

</blockquote>

**Comment by maryjom** [comment]
The TF agreed on language changes Option 2 for both Note 5 and Note 6 with appropriate changes to the word substitution. See [resolution from 8 August](https://www.w3.org/2024/08/08-wcag2ict-minutes#r01).  PR #467 incorporates the agreed changes (option 2 for Note 5 and Option 2 for Note 6) per the [Google doc](https://docs.google.com/document/d/1o6ruxbOKxAU6aWWz9Ac7P8DMi7lrIwXCy5DgvRzQZA4/edit#heading=h.3of6m81uhh6). 

This issue is being closed, since the PR has been merged.
