### ISSUE TITLE
Definition of 'style properties' needs different word substitution

### ISSUE THREAD

**Issue by mitchellevan** [w3c/wcag2ict#419]
The [definition of 'style properties'](https://www.w3.org/TR/wcag2ict-22/#dfn-style-properties) has a couple of issues

Issue: "rendered... by user agents or platform software" is correct for non-web documents with embedded markup, but it's not correct for non-web software such as an Electron app, where the software itself (not the underlying platform software) is responsible for the rendering.

Issue: The description of the last replacement isn't correct.

* It says 'replacing "user agent interface settings, user style sheets" with "user agent, platform software or other software settings"'
* But the actual replacement has the word "interface" still there.
* I recommend we keep "user style sheets" because [some software, such as Firefox](https://www.youtube.com/watch?v=y3CAALVAWEo), can respond to user style sheets

### Currently

This applies directly as written and as described in the WCAG 2 glossary, replacing “user agent(s)” with “user agent(s) or platform software”, "web content" with "content", replacing "in-line styles, author style sheets" with "programmatically-set styles", and replacing "user agent interface settings, user style sheets" with "user agent, platform software or other software settings".

With these substitutions, it would read:

<DL><DT>style property</DT><DD>

property whose value determines the presentation (e.g. font, color, size, location, padding, volume, synthesized speech prosody) of content elements as they are rendered (e.g. onscreen, via loudspeaker, via braille display) by <INS>**[[user agents](#user-agent) or [platform software](#platform-software)]**</INS>

Style properties can have several origins:

- <INS>**[User agent or platform software]**</INS> **default styles:** The default style property values applied in the absence of any author or user styles. Some <INS>**[content]**</INS> technologies specify a default rendering, others do not;
- **Author styles:** Style property values that are set by the author as part of the content (e.g. <INS>**[programmatically-set styles]**</INS>);
- **User styles:** Style property values that are set by the user (e.g. via <INS>**[user agent, platform software or other [software](#software)]**</INS> interface settings)
</DD></DL>

### Proposed

<DL><DT>style property</DT><DD>

property whose value determines the presentation (e.g. font, color, size, location, padding, volume, synthesized speech prosody) of content elements as they are rendered (e.g. onscreen, via loudspeaker, via braille display) by <INS>**[[user agents](#user-agent) or [software](#software)]**</INS>

Style properties can have several origins:

- <INS>**[User agent or platform software]**</INS> **default styles:** The default style property values applied in the absence of any author or user styles. Some <INS>**[content]**</INS> technologies specify a default rendering, others do not;
- **Author styles:** Style property values that are set by the author as part of the content (e.g. <INS>**[programmatically-set styles]**</INS>);
- **User styles:** Style property values that are set by the user (e.g. via <INS>**[user agent, platform software or other [software](#software) settings]**</INS>, user style sheets)
</DD></DL>

**Comment by olivia-hogan-stark** [comment]
@maryjom I made a [task in the Google Doc](https://docs.google.com/document/d/1o6ruxbOKxAU6aWWz9Ac7P8DMi7lrIwXCy5DgvRzQZA4/edit#heading=h.b905icjs4izt) for TF to review Mitch's word substitutions.

**Comment by maryjom** [comment]
The TF reached [resolution on 15 August.](https://www.w3.org/2024/08/15-wcag2ict-minutes#t04) to make the updates per Mitch's suggested edits and adding another "or" for better readability before "user style sheets". The changes will be merged once an editor has reviewed the PR.

**Comment by maryjom** [comment]
These changes have been incorporated into the editor's draft. Closing the issue as complete.
