### ISSUE TITLE
3.2.6 Consistent Help: does it need to be added in 'problematic for closed'?

### ISSUE THREAD

**Issue by mitchellevan** [w3c/wcag2ict#428]
### Currently

3.2.6 Consistent Help relies on the usual substitutions for "set of Web pages". The other four "set of Web pages" criteria are listed under [Success Criteria Problematic for Closed Functionality](https://www.w3.org/TR/wcag2ict-22/#success-criteria-problematic-for-closed-functionality), but 3.2.6 is not.

### Discussion of possible update

As I recall, I argued against including the "set of Web pages" criteria under "problematic for closed" because I considered the problems to be the same for closed functionality software are they are for open functionality software. However, in the end we reached consensus that four of these criteria should be listed under "problematic for closed" and I'm fine sticking with that consensus.

Given that the other four are there, it seems like a mistake not to list 3.2.6 there too.

I would be happy to accept any decision on this, I just wanted to confirm it wasn't missed inadvertently.

**Comment by maryjom** [comment]
TF reached consensus on 8 August to add the proposed bullet to the SC Problematic for Closed Functionality for 3.2.6 Consistent Help. This makes the handling of the "sets of..." SC consistent in this section. See the [TF resolution](https://www.w3.org/2024/08/08-wcag2ict-minutes#r02)  in the minutes
