### ISSUE TITLE
WCAG2ICT Project: Add from WCAG 2.2 - 3.3.7 Redundant Entry

### ISSUE THREAD

**Issue by maryjom** [w3c/wcag2ict#43]
- [x] Add [3.3.7 Redundant Entry](https://www.w3.org/TR/WCAG22/#redundant-entry) section (from WCAG 2.2)
- [x] Add in the [Understanding 3.3.7 Redundant Entry](https://www.w3.org/WAI/WCAG22/Understanding/redundant-entry.html) Intent and Benefits sections
- [x] Consider and write up whether there are any notes needed for application of this SC to non-web technologies

**Comment by olivia-hogan-stark** [comment]
From [3.3.9 Redundant Entry](https://www.w3.org/TR/WCAG22/#redundant-entry):

> Information previously entered by or provided to the user that is required to be entered again in the same [process](https://www.w3.org/WAI/WCAG22/Understanding/redundant-entry.html#dfn-process) is either:
> - auto-populated, or
> - available for the user to select.
> 
> Except when:
> - re-entering the information is [essential](https://www.w3.org/WAI/WCAG22/Understanding/redundant-entry.html#dfn-essential),
> - the information is required to ensure the security of the content, or
> - previously entered information is no longer valid.

**Comment by olivia-hogan-stark** [comment]
@maryjom I did not believe any additional notes are needed. This is ready for TF to review.

**Comment by maryjom** [comment]
@olivia-hogan-stark FYI, in the latest WCAG 2.2, this SC is 3.3.7 not 3.3.9.

**Comment by maryjom** [comment]
The guidance for this SC has been incorporated into the editor's draft and approved by the AG WG with no comments. See Issue #269 for their review.
