### ISSUE TITLE
Project Task: Remove editor's notes and text regarding horizontal review

### ISSUE THREAD

**Issue by maryjom** [w3c/wcag2ict#447]
This is a final draft task to clean out any remaining editor's notes or notes about reviews.
- [x] Remove editor's notes
- [x] Remove text: "Horizontal Review Groups are encouraged to provide further feedback during the Horizontal Review process." from the Privacy Considerations and Security Considerations sections
- [x] Clean up review information from the Status of this Document section.

**Comment by ChrisLoiselle** [comment]
@maryjom let me know when you want this "final task" to take place.

**Comment by maryjom** [comment]
@ChrisLoiselle I think this can wait until we're a couple of weeks before publication...just in case we wind up with too many substantive changes that might require another public draft before being finalized.

**Comment by ChrisLoiselle** [comment]
@maryjom did you have any particular areas on Remove editor's notes that you want me to investigate? I did an once over but didn't want to miss anything outstanding. Happy to take this one on!

**Comment by maryjom** [comment]
Once PR 447 is merged, this can be closed.

**Comment by maryjom** [comment]
Closed as completed.
