### ISSUE TITLE
WCAG2ICT Project: Update section - Background on Text / Command-line / Terminal Applications and Interfaces

### ISSUE THREAD

**Issue by maryjom** [w3c/wcag2ict#45]
- [x] Update section [How text interfaces are realized](https://w3c.github.io/wcag2ict/#how-text-interfaces-are-realized), if needed
- [x] Update section [How text applications have been made accessible via assistive technology](https://w3c.github.io/wcag2ict/#how-text-applications-have-been-made-accessible-via-assistive-technology), if needed
- [x] Update [Applying WCAG 2.0 to text applications](https://w3c.github.io/wcag2ict/#applying-wcag-2-0-to-text-applications), including the section title.

**Comment by mitchellevan** [comment]
@maryjom, I remember reviewing @JaninaSajka's PRs for this a while back. Would you please check status, and either mark this issue complete or summarize what's still needed? Thanks!
