### ISSUE TITLE
Added notes should not restart with note number 1

### ISSUE THREAD

**Issue by mitchellevan** [w3c/wcag2ict#462]
If issue #432 is fixed, the current issue will be "nice to have" not essential.

### SCs

The problem only occurs for a few SCs. It affects the SCs where WCAG contains one or more notes, those notes are not copied into the WCAG2ICT part, and the WCAG2ICT part adds one or more new notes.

#### SC 1.4.12 Text Spacing

Currently with PR #457, this SC lists "NOTE 1" and "NOTE 2" in the WCAG quotation, then "NOTE 1 (ADDED)" through "NOTE 4 (ADDED)" in the WCAG2ICT part.

While that is adequate for understanding, it would be nicer to restart the numbering. I propose that it should list "NOTE 1" and "NOTE 2" in the WCAG quotation, and "NOTE 3 (ADDED)" through "NOTE 6 (ADDED)" in the WCAG2ICT part.

#### SC 2.1.1 Keyboard

Like the previous example. Currently this SC lists 2 notes in the WCAG quotation, then 3 added notes in the WCAG2ICT part.

#### SC 1.3.4 Orientation

This is almost the same as the previous examples, except that the WCAG quotation only says "NOTE", not "NOTE 1".

Currently with PR #457, this SC lists "NOTE" in the WCAG quotation, then "NOTE 1 (ADDED)" and "NOTE 2 (ADDED)" in the WCAG2ICT part. I propose keeping "NOTE" in the WCAG quotation, but change to "NOTE 2 (ADDED)" and "NOTE 3 (ADDED)" in the WCAG2ICT part. Saying "NOTE" followed by "NOTE 2 (ADDED)" is good enough, and slightly better than saying "NOTE" followed by "NOTE 1 (ADDED)".

#### Special case: Different guidance for WCAG 2.0, 2.1, and 2.2

Issue #424 includes the unique note numbering for SC 4.1.1 Parsing.

### Glosssary

The issue for glossary definitions is a bit different from the issue for SCs. In the glossary, starting over with "note 1" also happens when the original WCAG note is copied for substitution.

- changes of context
- contrast ratio
- general flash and red flash thresholds
- keyboard interface
- relative luminance
- set of Web pages
- Web Page

Finally, if a note is added for the definition of 'large scale' as described in #436 comments, then this term will also be affected.

**Comment by mitchellevan** [comment]
> I wonder if we still need note numbering with this further processing. I know that the 2013 WCAG2ICT document had that, but original WCAG notes in the WCAG documents are not numbered.

After I reported #462, I saw @daniel-montalvo's idea in #432 comments about omitting the numbers. I think I like it.

An advantage of numbering is where there are many notes, making it easier for a reader to keep track of where they are. Examples:
- [SC 1.4.10 Reflow](https://deploy-preview-457--wcag2ict.netlify.app/#reflow)
- the [definition of 'relative luminance'](https://deploy-preview-457--wcag2ict.netlify.app/#dfn-relative-luminance)

Another advantage of numbering in WCAG2ICT is that WCAG started numbering its notes as of WCAG 2.2. Numbers in WCAG2ICT (if accurate) make it easier for a reader to understand how each note matches up with the corresponding WCAG note.

However, a disadvantage of numbering is the complexity. If we spend too much time tweaking note numbers, it's time we could have spent on other more important issues.

**Comment by maryjom** [comment]
@mitchellevan I think that the incorporation of "Added" to WCAG2ICT Notes and the documentation in replacement verbiage makes it clearer. Admittedly, there could still be slight confusion, but fairly easily explained. 

The only other option would be to remove numbering from the notes altogether. This can be done, if you think it's a better answer.

**Comment by mitchellevan** [comment]
Now that the editor's draft is showing the numbered notes, and notes indicated as "added", this combination is working well. I'm closing this issue, thanks!
