### ISSUE TITLE
Suggest slight clarification of audience and outcomes

### ISSUE THREAD

**Issue by matatk** [w3c/wcag2ict#464]
**Section:** https://www.w3.org/TR/wcag2ict-22/#introduction

APA appreciates the proposed Introduction section, but we believe that it would be helpful to mention the POUR principles explicitly, and to clarify the intended audience, and to reinforce the importance of obtaining user feedback when testing. We offer the following draft paragraph.

"This document provides informative guidance on mapping WCAG to non-web ICT contexts. Readers are encouraged to keep in mind the core framing principles which undergird WCAG Success Criteria and are commonly expressed by the acronym, POUR: Perceivable, Operable, Understandable, and Robust. Developers are also strongly encouraged to obtain testing input from persons with disabilities using applications and content. The sections below provide further details on how individual success criteria may be interpreted outside of the web context."

*[This issue comes from APA WG](https://lists.w3.org/Archives/Public/public-apa-admin/2024Aug/0006.html) - thanks to @Helixopp for this issue*

**Comment by maryjom** [comment]
Thank you for taking the time to review the WCAG2ICT public draft. Our task force will review your comment(s) and develop a response that we hope will address your concern(s).

**Comment by maryjom** [comment]
@Helixopp @matatk Thank you for your review of WCAG2ICT and your comment. 

The Task Force has made some edits to your suggested paragraph and added it to the Guidance in this Document section, as it fits well with what is stated there. You can view the exact changes made in PR #488 and you can read the text, in-context in the editor’s draft. See the second paragraph of the [Guidance in this Document section](https://w3c.github.io/wcag2ict/#guidance-in-this-document) (right after Note 1).

**Comment by matatk** [comment]
Thank you @maryjom and the whole TF; your changes address our concerns, so I'm closing this on behalf of APA WG.

*[minutes of the meeting in which we discussed this issue](https://www.w3.org/2024/09/11-apa-minutes#t06)*
