### ISSUE TITLE
Closed functionality list - suggested additions

### ISSUE THREAD

**Issue by matatk** [w3c/wcag2ict#466]
Section in document: 'Examples of technology that may have closed functionality'

The closed functionality list is accommodating, but could be expanded to include the following:

1. Medical devices such as digital blood pressure monitors, glucose metres, or other wearable devices.

2. Educational devices like whiteboard, smart boards.

3. Gaming platforms or consoles.

It's noted that some games consoles have extensive accessibility features (especially with respect to controller hardware, and sometimes including TTS functionality) but that, as per the note in this section of the document, not all of these aspects are open to user choice.

*[This issue comes from APA WG](https://lists.w3.org/Archives/Public/public-apa-admin/2024Aug/0006.html) - thanks to @nehamjadhav for this issue*

**Comment by maryjom** [comment]
Thank you for taking the time to review the WCAG2ICT public draft. Our task force will review your comment(s) and develop a response that we hope will address your concern(s).

**Comment by maryjom** [comment]
@nehamjadhav thank you for your review of the WCAG2ICT draft Note and your comment.

We have made adjustments to the examples of technology that may have closed functionality provided in the key term definition of “closed functionality” per your comment.  We added two bullets (# 1 and 2) as you suggested, and added the gaming examples to the bullet regarding entertainment technologies. You can read the changes in-context in the latest editor’s draft section for the key term “[closed functionality](https://w3c.github.io/wcag2ict/#closed-functionality)”.

Please respond to let us know that this sufficiently addresses your comment.

**Comment by matatk** [comment]
Thank you @maryjom and the whole TF; your changes address our concerns, so I'm closing this on behalf of APA WG.

*[minutes of the meeting in which we discussed this issue](https://www.w3.org/2024/09/11-apa-minutes#t06)*
