### ISSUE TITLE
Make small corrections/edits to the 'virtual keyboard' key term examples of ways virtual keyboards obtain input

### ISSUE THREAD

**Issue by maryjom** [w3c/wcag2ict#478]
Even though on 15 August we decided not to switch up the order of the sentence listing the ways a virtual keyboard takes input from the user, I think a couple of the examples need clarification/reordering as we had been drafting:

**Original text for the definition of "virtual keyboard":**

>**virtual keyboard**(as used in WCAG2ICT)
>any software that acts as a keyboard and generates output that is treated by other software as keystrokes from a keyboard
>
>NOTE: Speech, eye-gaze, sip-and-puff, sounds, switches, and codes have all been used by virtual keyboards as input that generates "keystroke" output.

**Proposed update to the note onlyand taking into account Olivia's ordering:** 

_Changes made: alphabetic ordering, change "codes" to "morse code", removing "sounds", and using sip-and-puff as an example of switches. Nothing was added or deleted from the list._

>**virtual keyboard**(as used in WCAG2ICT)
>any software that acts as a keyboard and generates output that is treated by other software as keystrokes from a keyboard
>
>NOTE: Eye-gaze, morse code, speech, and switches (e.g. sip-and-puff) have all been used by virtual keyboards as input that generates "keystroke" output.

**Comment by bruce-usab** [comment]
@maryjom , since we are making small changes, I suggest that "sounds" is unhelpful in this list.

**Comment by maryjom** [comment]
OK...will make additional edit to remove "sounds". PR coming soon so you can read in-context.

**Comment by ChrisLoiselle** [comment]
I reviewed, however may be premature as it appears we are bringing this to task force first for review. @maryjom

**Comment by maryjom** [comment]
The TF reached [resolution on the proposed changes to 'virtual keyboard' note's examples](https://www.w3.org/2024/08/22-wcag2ict-minutes.html#r01) in the 22 August meeting. These have been merged into the editor's draft.
