### ISSUE TITLE
Minor editorial: reference to EN 301 549 is not rendered correctly in Background

### ISSUE THREAD

**Issue by pday1** [w3c/wcag2ict#489]
Current editor's draft. 
The reference to EN 301 549 uses internal anchor instead of reference
See the 3rd paragraph in the Background section, 2nd sentence. 

"One example is [[etsi-en-301-549](https://w3c.github.io/wcag2ict/#bib-etsi-en-301-549)]"

I was unsure if this was a normal link that could be edited, or if the reference was pulled in from code and therefore needs extra changes.

@daniel-montalvo Is this reference incorporated through scripting, or can we manually edit the markdown?

**Comment by daniel-montalvo** [comment]
@pday1 

The scripts are not overwriting this.

However, I wonder what's wrong with this. The link points to our biblio section, which in turn points to the last published ETSI EN 301549 version, which  is from 2021.

**Comment by pday1** [comment]
Thanks @daniel-montalvo . The link is correct - it's just the way that it appears in the text. I'll make a PR to correct it. Thanks

**Comment by pday1** [comment]
Completed - see PR https://github.com/w3c/wcag2ict/pull/492
