### ISSUE TITLE
Principles and Guidelines say "undefined"

### ISSUE THREAD

**Issue by mitchellevan** [w3c/wcag2ict#514]
### Current behavior

This issue is occurring today in the [editor's draft](https://w3c.github.io/wcag2ict/).

For the Principles and the Guidelines, the word "undefined" is appearing between the name and the description.

Example: 

<blockquote>

<span>1. Perceivable</span>

undefined

Information and user interface components must be presentable to users in ways they can perceive.
</blockquote>

Screenshot of the example:

![Screenshot of the example](https://github.com/user-attachments/assets/5462a0f7-42bd-419f-8dac-1fac44d607ac)

The Criteria do not have this issue, because text such as "(Level A)" is appearing as expected in the Criteria.

### Expected behavior

For the Principles and Guidelines, there should be no text between the name and the description.

For the Criteria, text such as "(Level A)" should appear as it currently does.

**Comment by mitchellevan** [comment]
Hi @daniel-montalvo, please note this new issue. I'm guessing it's related to #507.

**Comment by maryjom** [comment]
@daniel-montalvo looks like some additional script or checking in the script would be needed to only be looking for and inserting a level if it is an SC, and not for principles and guidelines.
