### ISSUE TITLE
1.4.11: end quotation mark missing

### ISSUE THREAD

**Issue by detlevhfischer** [w3c/wcag2ict#524]
> This applies directly as written and as described in [Intent from Understanding Success Criterion 1.4.11](https://www.w3.org/WAI/WCAG22/Understanding/non-text-contrast.html#intent), replacing "user agent" with "user agent or platform software.

Should be (note final qutation mark):
> This applies directly as written and as described in [Intent from Understanding Success Criterion 1.4.11](https://www.w3.org/WAI/WCAG22/Understanding/non-text-contrast.html#intent), replacing "user agent" with "user agent or platform software."

**Comment by maryjom** [comment]
Thanks for catching the typo @detlevhfischer. It's fixed now.
