### ISSUE TITLE
Consistent use of closing quotes

### ISSUE THREAD

**Issue by daniel-montalvo** [w3c/wcag2ict#528]
In substitutions, we are using either '".' (quote first) and '."' (dot first).

I think we should make this consistent, preferably using '".' (quote first).

**Comment by ChrisLoiselle** [comment]
@daniel-montalvo are you updating where applicable? I'm not sure if you need help per what this issue states. Thanks for the clarity and help!

**Comment by maryjom** [comment]
@ChrisLoiselle Do you have time to take this up as a task? That would be helpful.

**Comment by ChrisLoiselle** [comment]
Please review https://github.com/w3c/wcag2ict/pull/530 and let me know if any other changes are needed.

**Comment by ChrisLoiselle** [comment]
@pday1 @maryjom @daniel-montalvo Please review https://github.com/w3c/wcag2ict/pull/530 and let me know if any other changes are needed.

**Comment by maryjom** [comment]
This has been fixed in PR #530. The only remaining instances of ." are when full sentences are quoted which is correct usage.
