### ISSUE TITLE
WCAG2ICT Project: Making the WCAG2ICT approach to the four "set of Web pages" SCs acceptable

### ISSUE THREAD

**Issue by mapluke** [w3c/wcag2ict#54]
# The problem
I believe that the way that the previous WCAG2ICT Task Force handled the guidance for handling the four SCs that referred to "a set of (or multiple) Web pages" (SCs 2.4.1, 2.4.5, 3.2.3, 3.2.4) to both non-Web software and to non-Web documents needs to be reconsidered. 

The team responsible for developing the European EN 301 549 standard were unable to accept the WCAG2ICT guidance for these four SCs and chose to exclude all four of these SCs from the sections dealing with non-Web software and the one dealing with non-Web documents. The U.S. Access Board also chose to exclude the application of these four SCs to non-Web software but did not exclude them for non-Web documents. 

Both groups presumably considered that it was of almost zero value, and an unnecessary complication, to include four requirements that were applicable to "a set of software programs" when it was almost impossible to find **any** real-world examples that met the very specific WCAG2ICT sets of software programs definition. The official European view on why we chose not to apply the four SCs to sets of non-Web documents is contained in the wording notes in EN 301 549 such as:
-  "The related web page requirement "Multiple ways" does not apply to single documents, but to a specific definition of "sets of documents" that are rare"

to explain their absence. There is no doubt that many sets of non-Web documents exist, although the number is less than might be expected when the very restrictive definition of such sets is taken into account.

I am **very** concerned that the omission of these SCs from the two most influential ICT accessibility standards is failing to address some common accessibility problems relating to consistency of identification and navigation that may frequently occur within the many millions of software and documents that do not belong to WCAG2ICT-defined "sets".  

A co-worker made a careful examination of the WCAG Understanding material and identified a lot of material that relates to issues *within a web* page rather than **between web pages in a set of web pages**. Some examples are:
- For 2.4.1:
	- [A Note indicates that "Even for web pages that are not in a set, if a web page has blocks of text that are repeated within the page it may be helpful (but not required) to provide a means to skip over them."](https://w3c.github.io/wcag/understanding/bypass-blocks.html)
- For 2.4.5:
	- The first two "Sufficient techniques" ([G125](https://w3c.github.io/wcag/techniques/general/G125) and [G64](https://w3c.github.io/wcag/techniques/general/G64)) uses examples such as the Table of Contents of WCAG 2.0 itself. Many of the links from these tables of content are within a single document and are not related to navigation between members of a set of documents.
- For 3.2.3:
	- The two advisory techniques [PDF14](https://w3c.github.io/wcag/techniques/pdf/PDF14) and [PDF17](https://w3c.github.io/wcag/techniques/pdf/PDF17) both clearly relate to navigation within a single PDF document and have nothing to do with being a member of a set. Such navigation is an extremely common and important feature of PDF documents and yet it is not currently addressed at all in EN 301 549 and it is not directly addressed in Section 508 because of the mapped SC's focus on sets of documents.
- For 3.2.4:
	- "Common sense" dictates that the exact same identification is equally important within a single software program as it is within a set of software programs. However the WCAG2ICT WG Note only applies it to the vanishingly small area of "sets of software programs" and does not apply it to the millions of individual software programs.

# A potential solution
I believe that the only practical solution is to entirely eliminate any reference to a "set of software" and a "set of documents" from the Task Force Note and to look for an alternative that does not rely on these concepts. Below is an initial proposal:

**3.2.4** Replace "a set of Web pages" with "a non-web document" or "software".
- This will result in:
  - **"Components that have the same functionality are identified consistently within a non-web document".** 
  - **"Components that have the same functionality are identified consistently within software".** 

A very simple and highly useful SC when applied to all software and documents.
 
              
**3.2.3** Replace "on multiple Web pages" with "" and “a set of Web pages” with "a non-web document" or "software".
- This will result in:
  - **"Navigational mechanisms that are repeated within a non-web document occur in the same relative order each time they are repeated, unless a change is initiated by the user."** 
  - **"Navigational mechanisms that are repeated within software occur in the same relative order each time they are repeated, unless a change is initiated by the user."
		
This seems to me to work fine.
 
 
**2.4.5** Replace "Web page" with "target destination" replace "a set of Web pages" with "a non-web document" or "software".
- This will result in:
  - **"More than one way is available to locate a target destination within a non-web document except where the target destination is the result of, or a step in, a process."** 
  - **"More than one way is available to locate a target destination within software except where the target destination is the result of, or a step in, a process."**
		
This needs a definition of "target destination", but this might not be too difficult - it is what is located i.e. the destination that a link, or other control action jumps to.
 
**2.4.1** Replace "on multiple Web pages" with " within a non-web document" or "software". 
- This will result in:
  - **"A mechanism is available to bypass blocks of content that are repeated within a non-web document".** 
  - **"A mechanism is available to bypass blocks of content that are repeated within software ".** 
		
This might be a little vague in terms of meaning or testability, but this exact scenario is currently addressed by a note in the understanding text for 2.4.1.

**Comment by patrickhlauke** [comment]
particularly for "Multiple ways", I'd say it makes very little sense in the context of, say, a native application. Think for instance a typical iOS/Android app, where each "page"/screen/view is accessed from a set of tabs/buttons at the bottom of the screen. And related screens being opened essentially as overlays/screen-filling modals/replacements of the entire screen, with no general navigation visible at all in those cases.

**Comment by mraccess77** [comment]
I'm glad we are taking another look at this - one challenge with the proposal is that it could be considered to expand the scope of the SC - in particular with 2.4.5 which was between pages and not within a page.  With SC 3.2.4 it would extend identification requirements within the same screen of an app or page of a document which we don't have for web content.

We might also want to reexamine the limitations of SC 2.4.2 Page titles in software to the app as a whole - but that is a separate discussion.

**Comment by mapluke** [comment]
One of the absolute constraints we had in WCAG2ICTv1 was that saying that an SC was not applicable to software or documents was not an option we were allowed. 

This forced us into the tactic of finding a simple and very direct mapping. This led us to define the troublesome concepts of sets of documents and sets of software. I think that few, if any of us liked this solution, but it was the only one that fitted the constraints. I really think that the solution to applying 2.4.2 to software is a non-starter - it seems to imply that all spreadsheet apps should be titled "spreadsheet"! It rapidly becomes impossible to imagine titles that can "describe the topic or purpose" for many of today's complex multifunctional apps.

**Comment by mapluke** [comment]
@patrickhlauke I fully understand, and agree, that mapping 2.4.5 - Multiple Ways to software in the logical way that I have done may not result in a useful, or even practical, solution. In this case, I think that the sensible answer is to say that 2.4.5 **should not be** applied to software rather than asking that it should be applied to (almost non-existent) "sets of software".

**Comment by mapluke** [comment]
@mraccess77 I fully understand and agree with what you are saying about potentially extending the scope beyond what WCAG requires for web content. My feeling is that when SCs like 2.4.5 and 3.2.4 were written the general style and implementation of websites involved a lot more linking between pages and a lot less within page linking. Modern web apps look very different from this model and obviously look much like the software apps that we are trying to address.

Modifying these SCs to address both within page and between page scenarios is not an available option, so these have remained unchanged from their roots back in WCAG 1.0. Just because we do not have the option to revisit and adapt the w eb based SCs, t would be a shame if these historic limitations constrain how we might make WCAG more applicable to modern software applications.

In my original issue description I did mention some content in the various SCs that are really more targetted to within page interaction rather than between page interaction.

**Comment by bruce-usab** [comment]
With the Revised 508 Standards ended up at `dont want` for those four SC:
- (non-web documents)[https://www.access-board.gov/ict/#E205.4]
- (non-web software)[https://www.access-board.gov/ict/#E207.2] &mdash; 2nd exception

With the benefit of hindsight, maybe Access Board could/should have tried harder, or maybe not treated them both the same?  

The concept of a "document within a set of documents" is coherent.  The 2.4.5 analog, "more than one way to locate a document within a collection/folder/group/set of documents" is coherent.  The other three SC are not useful for non-web documents.

The concept of a "set of software" is not unimaginable, but it was a distraction to discuss.  A software analog for 2.4.5 is not useful. OTHO one does not have to be too created to come up with software-oriented analogs for the other three.

The TF did not feel at liberty to table discussion on "set of Web pages".  Likewise, the TF did not feel at liberty to substitute close analogs.  Personally, given limited time, I would prefer to address AAA SC before "set of Web pages".

**Comment by GreggVan** [comment]
Hmmmmm

I agree that 2.4.2 is not something that makes a lot of sense for software as written  - using the "set of" construct. 

But the way it was described below can be misread.

This was not a restriction in WCAG2ICT - other than we could not re-write any of the SC. 
We were asked if they could apply as written substituting     Software and   Non-web content for    Web Page

A couple SC said ’set of web pages"   —  which would translate into Set of Software or Set of non-text content.   
The group found that the SC did/would apply — but that there were precious few examples in the real world.  (We did find 2 examples of sets of software and mention of  third but I never saw it).   We felt that thought it technically would apply — that we would never have included an SC for something that rare.   SO our final finding said that it did apply but would be extremely rare in the real world.

So we never had to define such concepts or were forced to - though we did run into them. 

Also 2.4.2 does not say that all pages (or documents or spreadsheets) would need to have the same title.   It just means that the identifier (title) for a button that does the same thing in different places in a set of things — should have the same name if it did the same thing.    Submit for example.    Or "Save".      A great example of where this is not done is Wordpress.  Where the save button is sometimes called "save"  and other places called  "update"  or  "create new xxxx"  (which is really confusing if you just filled out a page and that was the same name of the button that gave you new blank page!   If I click it will it throw away what I just did and give me a new blank page?  No- it means save the new page you just created.  Then click on a different button with the same name to create another new page )   

gregg

------------------------------
Gregg Vanderheiden
***@***.***

**Comment by GreggVan** [comment]
Interesting 
The answer differs deepening on how we ask it.


If the question is  — Would 2.4.5 apply as written to software (sets of software in this case)   the answer is yes.  It makes sense and would apply.  But it will almost never occur - since there are few ’sets of software’ like this. 

If the question is  — Should we include the SC in a list of requirements for software - the answer is no.   It makes sense but will almost never occur - since there are few ’sets of software’ like this.  So it is a waste of space and focus to add it.    
The only exception would be if one could say  "All of the SC apply with the words  software and  non-web content  substituted for web page or page  —  and thus have a simple finding rather than listing all but one or two where this was true but of no particular value.
In 508 - they chose to use the above bullet approach
In EN 301 549 - where each provision is re-listed for software, web, and non-web content - they simply didnt include those couple provisions in the software  or document sections. 


gregg

------------------------------
Gregg Vanderheiden
***@***.***

**Comment by GreggVan** [comment]
This is a very good point

Those SC were focused on web page based sites.
Web-apps are more like software - and, using the WCAG Definition of page  " Most web apps are a single web page".   Hence these SC would not apply to those web apps.   There are some web apps that are broken out across URLS — and then each URL would constitute a page - and then these SC would apply.

But for single URL Web Apps — they would not apply since they are only one "web page"

I would say that WebApps were software except that they are still rendered through a user agent — so are more like software in some ways and more like web pages in others. 

gregg

------------------------------
Gregg Vanderheiden
***@***.***

**Comment by GreggVan** [comment]
Agree with this.

But I don’t think "set of web pages" needs to consume much time.    I think everyone agrees on the facts (as least they did at the end of the last one).  The only difference was in how to handle them. 
I think it is best summarized as 

FACTS
	- the "set of" provisions are really focused on page-based websites
	- the "set of" provisions are coherent and meaningful when applied to non-web documents and software
	- however "sets of" non-web documents and software are pretty rare  (or extremely rare for software)

WHAT DO DO ABOUT IT
	EITHER
		- go ahead and let them stand - but note that they are pretty/extremely rare
	OR
		- say those provisions should just be ignored since they are pretty/exteremely rare


508 for simplicity did option 1 since it didnt repeat all the provisions  (though it relied on WCAG2ICT to state that they were rare)
EN 301 549 went with option 2 since the did repeat all the provisions within different sections for  Web, non-web content, and non-web software  - and could easily just leave them out (or leave them as blank numbered provisions - to preserve numbering sequence) 

I think we could get to the same place in the new group pretty quickly as well

NOTE: that it took us a much longer time in the past because 
	1) we were trying to see if VIEWS or something else could replace the concept of pages (and failed)
	2) we took time to search and find out whether "sets of"  non-web content and software   were real animals in the wild or not.  (Answer - yes but….. not really enough to talk about)


gregg

------------------------------
Gregg Vanderheiden
***@***.***

**Comment by detlevhfischer** [comment]
@GreggVan wrote:

> EN 301 549 went with option 2 since the did repeat all the provisions within different sections for  Web, non-web content, and non-web software  - and could easily just leave them out (or leave them as blank numbered provisions - to preserve numbering sequence)

I think you got this one wrong. The following SCs have been left out in the EN 301 549 provisions for software (clause 11):

- 11.2.4.1 Bypass blocks (Void)
- 11.2.4.2 Page titled (Void)
- 11.2.4.5 Mulatiple ways (Void)
- 11.3.1.2 Language of parts (Void)
- 11.3.2.3 Consistent navigation (Void)
- 11.3.2.3 Consistent Identification (Void)

I checked the latest versions but I believe it has always been this way.

**Comment by mapluke** [comment]
@GreggVan you say that:

> Also 2.4.2 does not say that all pages (or documents or spreadsheets) would need to have the same title.   It just means that the identifier (title) for a button that does the same thing in different places in a set of things — should have the same name if it did the same thing.    Submit for example.    Or "Save".      A great example of where this is not done is Wordpress.  Where the save button is sometimes called "save"  and other places called  "update"  or  "create new xxxx"  (which is really confusing if you just filled out a page and that was the same name of the button that gave you new blank page!   If I click it will it throw away what I just did and give me a new blank page?  No- it means save the new page you just created.  Then click on a different button with the same name to create another new page )

but surely that is not correct. 2.4.2 is "Page titled" and the [Understanding page](https://w3c.github.io/wcag/understanding/page-titled.html) clearly states (with my added emphasis) that:

> The intent of this Success Criterion is to help users find content and orient themselves within it by ensuring that **each Web page** has a descriptive title. 
The rest of the understanding text indicates nothing similar to your interpretation that the SC is to do with things like the titles of buttons.


So, I think that the reasons given in **both** the notes in EN 301 549 are still correct:

> NOTE 1:	The related web page requirement "Page titled" does not apply to single software programs, but to a specific definition of "sets of software programs" that are extremely rare.
> NOTE 2:	Although the name of a software product could be a sufficient title if it describes the topic or purpose, software names are trademarked and trademark names cannot by law be descriptive names. It is not practical to make software names both unique and descriptive.

The following note was also added in EN 301 549 to exclude SC 3.1.2 (Language of parts):

> NOTE:	To apply the related web page requirement for "Language of parts" to software would require the marking-up of all text in all locations within the software. This would be impossible so an equivalent is not included in this clause on software requirements.
It is possible better wording could have been chosen, but I think that this still applies.

The current WCAG2ICT note implies that language of parts **should** be applied to software. If we think that this is either not possible or will never be attempted in non-Web software then we shouldn't imply that it is by suggesting that all that needs to happen is to map "page" to "software" and then apply that reworded to software.

**Comment by mapluke** [comment]
@bruce-usab wrote:

> The concept of a "document within a set of documents" is coherent. The 2.4.5 analog, "more than one way to locate a document within a collection/folder/group/set of documents" is coherent. The other three SC are not useful for non-web documents.

That is completely true, but we should remind ourselves that the [WCAG2ICT definition of a "Set of Documents"](https://www.w3.org/TR/wcag2ict/#keyterms_set-of-documents) is very specific and would exclude the vast majority of collections of documents that might be packaged together:

> group of documents that are published together, and where the items all refer to each other by name or link
> 
> Note 1: Republishing or bundling previously published documents as a collection does not constitute a set of documents.
> 
> Note 2: If a set is broken apart, the individual parts are no longer part of a set, and would be evaluated as any other individual document is evaluated.

**Comment by mapluke** [comment]
@bruce-usab wrote:

> The concept of a "document within a set of documents" is coherent. The 2.4.5 analog, "more than one way to locate a document within a collection/folder/group/set of documents" is coherent. The other three SC are not useful for non-web documents.

That is completely true, but we should remind ourselves that the [WCAG2ICT definition of a "Set of Documents"](https://www.w3.org/TR/wcag2ict/#keyterms_set-of-documents) is very specific and would exclude the vast majority of collections of documents that might be packaged together:

> group of documents that are published together, and where the items all refer to each other by name or link
> 
> Note 1: Republishing or bundling previously published documents as a collection does not constitute a set of documents.
> 
> Note 2: If a set is broken apart, the individual parts are no longer part of a set, and would be evaluated as any other individual document is evaluated.

**Comment by mapluke** [comment]
@bruce-usab wrote:

> The concept of a "document within a set of documents" is coherent. The 2.4.5 analog, "more than one way to locate a document within a collection/folder/group/set of documents" is coherent. The other three SC are not useful for non-web documents.

That is completely true, but we should remind ourselves that the [WCAG2ICT definition of a "Set of Documents"](https://www.w3.org/TR/wcag2ict/#keyterms_set-of-documents) is very specific and would exclude the vast majority of collections of documents that might be packaged together:

> group of documents that are published together, and where the items all refer to each other by name or link
> 
> Note 1: Republishing or bundling previously published documents as a collection does not constitute a set of documents.
> 
> Note 2: If a set is broken apart, the individual parts are no longer part of a set, and would be evaluated as any other individual document is evaluated.

**Comment by GreggVan** [comment]
> On Nov 3, 2022, at 8:53 AM, mapluke ***@***.***> wrote:
> 
> 
> @GreggVan <https://github.com/GreggVan> you say that:
> 
> Also 2.4.2 does not say that all pages (or documents or spreadsheets) would need to have the same title. It just means that the identifier (title) for a button that does the same thing in different places in a set of things — should have the same name if it did the same thing. Submit for example. Or "Save". A great example of where this is not done is Wordpress. Where the save button is sometimes called "save" and other places called "update" or "create new xxxx" (which is really confusing if you just filled out a page and that was the same name of the button that gave you new blank page! If I click it will it throw away what I just did and give me a new blank page? No- it means save the new page you just created. Then click on a different button with the same name to create another new page )
> 
> but surely that is not correct. 2.4.2 is "Page titled" and the Understanding page <https://w3c.github.io/wcag/understanding/page-titled.html> clearly states (with my added emphasis) that:
> 
> The intent of this Success Criterion is to help users find content and orient themselves within it by ensuring that each Web page has a descriptive title.
> The rest of the understanding text indicates nothing similar to your interpretation that the SC is to do with things like the titles of buttons.
> 
Sorry  had the wrong SC number.

Yes . 2.4.2  says that each must have a descriptive title — but that does not mean they have to have the SAME title - which is what you mentioned.  


> So, I think that the reasons given in both the notes in EN 301 549 are still correct:
> 
> NOTE 1: The related web page requirement "Page titled" does not apply to single software programs, but to a specific definition of "sets of software programs" that are extremely rare.
> NOTE 2: Although the name of a software product could be a sufficient title if it describes the topic or purpose, software names are trademarked and trademark names cannot by law be descriptive names. It is not practical to make software names both unique and descriptive.
> 
I think that trade names for software do count as descriptive names.   They give the person a handle that they can use to know what page they are on.     I don’t know that WCAG ever said trade names could not be used as the descriptive name for a page - as long as all the pages didnt have the same name.   (For software - that would mean having different programs all with the same name).   I think the phrase "descriptive" was over-interpreted here. 

> The following note was also added in EN 301 549 to exclude SC 3.1.2 (Language of parts):
> 
> NOTE: To apply the related web page requirement for "Language of parts" to software would require the marking-up of all text in all locations within the software. This would be impossible so an equivalent is not included in this clause on software requirements.
> It is possible better wording could have been chosen, but I think that this still applies.
> 
> The current WCAG2ICT note implies that language of parts should be applied to software. If we think that this is either not possible or will never be attempted in non-Web software then we shouldn't imply that it is by suggesting that all that needs to happen is to map "page" to "software" and then apply that reworded to software.
> 
This is one that I think is a problem for all non-markup technologies.     It is not just for software that I think this should be revisited.   I think WCAG 3 should re-look at this.

**Comment by GreggVan** [comment]
I think that is what I said

That option two was to not include them  but preserve the numbering. 
I said "blank numbered provisions"  — and what I meant was they included the number (and the title) but not the provision. 

gregg

———————————
Professor, University of Maryland, College Park
Founder and Director Emeritus , Trace R&D Center, UMD
Co-Founder Raising the Floor. http://raisingthefloor.org
The Global Public Inclusive Infrastructure (GPII) http://GPII.net
The Morphic project  https://morphic.org

**Comment by bruce-usab** [comment]
Thanks @mapluke &mdash; I just meant from the perspective of considering those four (2.0) SC **_absent_** what the TF put into the wcag2ict work product.

As you note, the wcag2ict definitions are precise and nuanced.  But, as an example, most laypeople would not assume that a group of documents that are published together would all **necessarily** refer to each other by name or link.  That is a detail added to make the work seamlessly.  It is not intuitive.  This very specialized use of the term "set of documents" was a factor in the Access Board not applying those four SC to non-web documents.

**Comment by GreggVan** [comment]
+1

gregg

———————————
Professor, University of Maryland, College Park
Founder and Director Emeritus , Trace R&D Center, UMD
Co-Founder Raising the Floor. http://raisingthefloor.org
The Global Public Inclusive Infrastructure (GPII) http://GPII.net
The Morphic project  https://morphic.org

**Comment by mraccess77** [comment]
In my opinion with mobile apps and Windows software applications applying SC 3.1.2 language of parts is possible - but applying SC 3.1.1 for the entire application is not as there is not generally a good way to communicate the language of the entire app.    In addition, users of screen readers would likely put their assistive technology into that language when using an app (at least from my experience of how they work).

I like the direction 11.3.1.1.1 of EN 301 549 goes with the Note - but the note still doesn't fully address the issue as it says software that renders in that locale would pass without specifying that this information needs to be detectable by user agents (assistive technology) - although it implies that in the next sentence without requiring it).

The note then goes on to imply it can conform but not for the other locales - which implies you can conform for some languages. if even 11.3.1.1.1 is not met.

NOTE 1: Where software platforms provide a "locale / language" setting, applications that use that setting and render their interface in that "locale / language" would comply with this success criterion. Applications that do not use the platform "locale / language" setting but instead use an accessibility-supported method for exposing the human language of the software would also comply with this success criterion.
Applications implemented in technologies where assistive technologies cannot determine the human
language and that do not support the platform "locale / language" setting may not be able to meet this success criterion in that locale / language.

**Comment by mapluke** [comment]
I believe that this table summarises the status and where the above comments leave us:
| SC                                    | Single web pages                                                                                                                   | Set of web pages              | Single Documents                                                 | Set of documents                                                                                    | Single software program                                                                                 | Set of software                                                             |
| ------------------------------------- | ---------------------------------------------------------------------------------------------------------------------------------- | ----------------------------- | ---------------------------------------------------------------- | --------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------------- | --------------------------------------------------------------------------- |
| 2.4.1 – Bypass blocks                 | **No such SC in WCAG**, although a Note in the understanding acknowledges its relevance.                                           | **Applies without exception** | **Could apply** if “on multiple Web pages” is replaced with “”.  | **1:1 mapping** if “web pages” is replaced by “non-web documents”. Not in EN 301 549 or Section 508 | **Could apply** if “on multiple Web pages” is replaced with “”.                                         | Of no use, therefore **“does not apply”.** Not in EN 301 549 or Section 508 |
| 2.4.2 – Page titled                   | **Applies without exception**                                                                                                      | **N/A**                       | **Applies without exception.**                                   | **N/A**                                                                                             | **Makes no sense. \*** Not in EN 301 549.                                                               | **N/A**                                                                     |
| **2.4.5 – Multiple ways**             | **No such SC in WCAG**, although two techniques in the understanding seem to describe a single-page example.                       | **Applies without exception** | **N/A**                                                          | **1:1 mapping** if “web pages” is replaced by “non-web documents”. Not in EN 301 549 or Section 508 | **N/A**                                                                                                 | Of no use, therefore **“does not apply”.** Not in EN 301 549 or Section 508 |
| 3.1.2 – Language of parts             | **Applies without exception**                                                                                                      | **N/A**                       | **1:1 mapping** if “web page” is replaced by “non-web document”. | N/A                                                                                                 | @mraccess77  argues that this is appropriate for single apps (and that 3.1.1 is not). Not in EN 301 549. | **N/A**                                                                     |
| **3.2.3 – Consistent navigation**     | **No such SC in WCAG**, although two techniques clearly describe a within-page example.                                        | **Applies without exception** |  **Could apply** if "on multiple Web pages" is replaced with "" and “a set of Web pages” is replaced with "a non-web document".                                                                | **1:1 mapping** if “web pages” is replaced by “non-web documents”. Not in EN 301 549 or Section 508 | **Probably inapplicable.**                                                                                                        | Of no use, therefore **“does not apply”.** Not in EN 301 549 or Section 508 |
| **3.2.4 – Consistent identification** | **No such SC in WCAG**, although it is common sense that identification should be consistent within page as well as between pages. | **Applies without exception** | **Could apply** if "set of Web pages" is replaced with "non-web document".                                                                | **1:1 mapping** if “web pages” is replaced by “non-web documents”. Not in EN 301 549 or Section 508 | **Could apply** if "set of Web pages" is replaced with "software".                                                                                                         | Of no use, therefore **“does not apply”.** Not in EN 301 549 or Section 508 |

@bruce-usab makes the point that Section 508 might have looked at the "set of documents" SCs differently to the "set of software" SCs and have included some. But he further states that omitting them might still be the best policy because the risk that testers would apply these SCs to any collection of documents, rather than one that meets the stringent "set of software" definition. This could result in documents that are part of a collection of documents being failed for not providing links to other documents that did not exist when the document under test was written. So the WCAG2ICT statement that they can be applied to sets is perfectly correct, but that choosing to not include them in Section 508 and EN 301 549 might well still be the most sensible choice.

The biggest take-home to me is that there seems to be a very strong case for removing all references to "sets of software" from the WCAG2ICT Note and to either:

- explicitly state that each of the "sets of web pages" SCs **does not apply** to software;
- or look at applying them to software in a "within-document/software" way that I have suggested earlier.

I do not think that we should just leave these as they currently are as it potentially reflects badly on W3C when both EN 301 549 and Section 508 reject these few WCAG2ICT conclusions as being of no realistic value.
