### ISSUE TITLE
Success Criterion 2.5.4: Motion Actuation (Level A)

### ISSUE THREAD

**Issue by samogami** [w3c/wcag2ict#78]
From [Success Criterion 2.5.4](https://www.w3.org/TR/WCAG22/#motion-actuation):

> [Functionality](https://www.w3.org/TR/WCAG22/#motion-actuation) that can be operated by device motion or user motion can also be operated by [user interface components](https://www.w3.org/TR/WCAG22/#dfn-user-interface-components) and responding to the motion can be disabled to prevent accidental actuation, except when:
>
> * **Supported Interface:** The motion is used to operate functionality through an [accessibility supported](https://www.w3.org/TR/WCAG21/#dfn-accessibility-supported) interface;
> * **Essential:** The motion is [essential](https://www.w3.org/TR/WCAG21/#dfn-essential) for the function and doing so would invalidate the activity.

##### Additional Guidance When Applying Success Criterion 2.5.4 to Non-Web Documents and Software:

* This applies directly as written, and as described in [Intent from Understanding Success Criterion 2.5.4](https://www.w3.org/WAI/WCAG22/Understanding/motion-actuation.html)

**Comment by maryjom** [comment]
@samogami Is this ready for the TF to review?

**Comment by maryjom** [comment]
Created [survey for 2.5.4](https://www.w3.org/2002/09/wbs/55145/WCAG2ICT-Motion-Actuation/) due on 9 February.

**Comment by pday1** [comment]
Resolution passed. I'll make a stab at incorporating into the editors draft

**Comment by pday1** [comment]
Now in pull request 
https://github.com/w3c/wcag2ict/pull/102

**Comment by maryjom** [comment]
This has been merged into the editor's draft.

**Comment by maryjom** [comment]
AG WG has a [survey](https://www.w3.org/2002/09/wbs/55145/WCAG2ICT-First-AG-review-4-sc/) open until 9 March with AG WG survey results discussion at a TBD future date (after CSUN conference).

**Comment by maryjom** [comment]
Complete and merged. Approved in the AG WG meeting on 21 March 2023.
