### ISSUE TITLE
Status of this document - patent policy links go to a 2004 version

### ISSUE THREAD

**Issue by maryjom** [w3c/wcag2ict#95]
There is a paragraph in the Status of this document section that has 3 old link URLs to various parts of the patent policy. They link to a 2004 version of the patent policy rather than the current one, dated 15 September 2020. 
>This document was produced by a group operating under the [1 August 2017 W3C Patent Policy](https://www.w3.org/Consortium/Patent-Policy-20170801/). W3C maintains a [public list of any patent disclosures](https://www.w3.org/groups/wg/ag/ipr) made in connection with the deliverables of the group; that page also includes instructions for disclosing a patent. An individual who has actual knowledge of a patent which the individual believes contains [Essential Claim(s)](https://www.w3.org/Consortium/Patent-Policy-20170801/#def-essential) must disclose the information in accordance with [section 6 of the W3C Patent Policy](https://www.w3.org/Consortium/Patent-Policy-20170801/#sec-Disclosure).

How do we get this updated, as I cannot find which file produces this part of the status of this document text. 

@daniel-montalvo can you tell me how to get this fixed?

**Comment by daniel-montalvo** [comment]
@maryjom 

Thanks to @michael-n-cooper we found out that this is correct behavior, as WCAG2ICT is under the [2019 Charter](https://www.w3.org/2019/12/ag-charter#patentpolicy). As the new Charter is in effect, we will move to the new Patent Policy.

**Comment by maryjom** [comment]
@daniel-montalvo the problem is that the link text says it's linking to the 2017 patent policy, but when you use the link it actually goes to a 2004 patent policy.

**Comment by daniel-montalvo** [comment]
@maryjom 

I agree that this Patent  Policy page may be confusing. If first mentions 2004 but the sub heading says:

> 5 February 2004 (updated 1 August 2017)

And then in the Status of This Document:

> This is the 5 February 2004 version of the W3C Patent Policy, updated 1 August, 2017. 

The Patent Policy page could probably just say "updated 2017" because the mention to the 2004 part is confusing.

We are linking to a Patent Policy that was updated in 2017, so i'd say we are OK here for now.
