### ISSUE TITLE
Success Criterion 2.5.3: Label in Name (Level A)

### ISSUE THREAD

**Issue by devchan4188** [w3c/wcag2ict#99]
From [Success Criterion 2.5.3](https://www.w3.org/TR/WCAG22/#label-in-name):

>For [user interface components](https://www.w3.org/TR/WCAG22/#dfn-user-interface-components) with [labels](https://www.w3.org/TR/WCAG22/#dfn-labels) that include [text](https://www.w3.org/TR/WCAG22/#dfn-text) or [images of text](https://www.w3.org/TR/WCAG22/#dfn-images-of-text), the [name](https://www.w3.org/TR/WCAG22/#dfn-name) contains the text that is presented visually.

>NOTE
A best practice is to have the text of the label at the start of the name.

##### Additional Guidance When Applying Success Criterion 2.5.3 to Non-Web Documents and Software:

This applies directly as written, and as described in [Intent from Understanding Success Criterion 2.5.3](https://www.w3.org/WAI/WCAG22/Understanding/label-in-name.html) (also provided below).

> **Note:** for Non-Web Documents and Software the Accessible Name and Description Computation specification depends on the attributes provided by the specific platform APIs.

**Comment by maryjom** [comment]
@devchan4188 I think this might also need the standard pointer text to the closed product section:
>NOTE
>See also the discussion on [Closed Functionality](http://w3c.github.io/wcag2ict/#closed-functionality).

and in the section [Success Criteria Problematic for Closed Functionality](https://deploy-preview-97--wcag2ict.netlify.app/#success-criteria-problematic-for-closed-functionality) a bullet needs to be added:
>- [2.5.3 Label in Name](https://www.w3.org/TR/WCAG22/#label-in-name) —requires information in a programmatically determinable form; specifically, the programmatic name contains the text of the visual label;

**Comment by mitchellevan** [comment]
For the record, iOS has not just an accessible name, but also the possibility of a [list of voice control labels](https://developer.apple.com/news/?id=4dcwl3iv). That said, I would not include this detail in our current scope for WCAG2ICT. It would make more sense somewhere in Understanding and Techniques, not in our current work plan. It doesn't change 2.5.3 anyway, just enhances it.

**Comment by mitchellevan** [comment]
> Note: for Non-Web Documents and Software the Accessible Name and Description Computation specification depends on the attributes provided by the specific platform APIs.

Nits:
* use more lowercase
* omit "description" and "specification"

I would not add this note to the criterion, but rather merge it into the following draft note for the [glossary definition of "name"](https://w3c.github.io/wcag2ict/#dfn-name):

> NOTE “AccessibleName” (or whatever it is called in different APIs) of the Accessibility API of the platform is an example of such a name.

Proposed updated note for the "name" definition (with examples borrowed from [core-aam](https://www.w3.org/TR/core-aam-1.2/#accessible-names-and-descriptions)):

> Note: for non-web documents and software, the accessible name computation depends on object properties in accessibility APIs provided by the platform. "Name" and "AXTitle" are examples of such object properties.

**Comment by loicmn** [comment]
I agree with @mitchellevan proposal:

1. Don't have a note in 2.5.3, but have it in the definition of "name"
2. Replacing the current note in "name" by his proposal

**Comment by maryjom** [comment]
Incorporating all of the changes suggested so far into a full draft (to help with others who haven't reviewed/commented yet):
From [Success Criterion 2.5.3](https://www.w3.org/TR/WCAG22/#label-in-name):

>For [user interface components](https://www.w3.org/TR/WCAG22/#dfn-user-interface-components) with [labels](https://www.w3.org/TR/WCAG22/#dfn-labels) that include [text](https://www.w3.org/TR/WCAG22/#dfn-text) or [images of text](https://www.w3.org/TR/WCAG22/#dfn-images-of-text), the [name](https://www.w3.org/TR/WCAG22/#dfn-name) contains the text that is presented visually.

>NOTE
A best practice is to have the text of the label at the start of the name.

##### Additional Guidance When Applying Success Criterion 2.5.3 to Non-Web Documents and Software:

This applies directly as written, and as described in [Intent from Understanding Success Criterion 2.5.3](https://www.w3.org/WAI/WCAG22/Understanding/label-in-name.html) (also provided below).
**Note:** See also the discussion on [Closed Functionality](http://w3c.github.io/wcag2ict/#closed-functionality).

In the section [Success Criteria Problematic for Closed Functionality](https://deploy-preview-97--wcag2ict.netlify.app/#success-criteria-problematic-for-closed-functionality) a bullet needs to be added:
- [2.5.3 Label in Name](https://www.w3.org/TR/WCAG22/#label-in-name) —requires information in a programmatically determinable form; specifically, the programmatic name contains the text of the visual label;

In the definitions section, the WCAG2ICT guidance part would read: 
#### Additional Guidance When Applying the Definition of “name” to Non-Web Documents and Software:
This applies directly as written and as described in the WCAG 2.2 glossary, replacing “Web content” with “content” and adding “or by accessibility features of software” after “assistive technology” in Note 1.

With this substitution, it would read:

name
>text by which software can identify a component within **[[content](https://www.w3.org/TR/wcag2ict/#wcag2ict-def_content)]** to the user
>
>Note 1: The name may be hidden and only exposed by assistive technology **[or by accessibility features of software]**, whereas a [label](https://www.w3.org/TR/wcag2ict/#wcag2ict-def_label) is presented to all users. In many (but not all) cases, the label and the name are the same.
>
>Note 2: This is unrelated to the name attribute in HTML.
>
**Note:** For non-web documents and software, the accessible name computation depends on object properties in accessibility APIs provided by the platform. "Name" and "AXTitle" are examples of such object properties..

**Comment by maryjom** [comment]
One thing to note: **IF** we change this note on "name", a similar statement to "“AccessibleName” (or whatever it is called in different APIs) of the Accessibility API of the platform is an example of such a name." already exists in the WCAG2ICT interpretations for "role" and "structure". That statement is:
> “AccessibleRole” (or however it is called in different APIs) of the Accessibility API of the platform is an example of such a role.

So if we change this note, we should use consistent language.

Perhaps the notes should read "The user agent or platform software computes the name from object properties set by the non-web document or software and exposes that name to assistive technology via the platform accessibility API. "Name" and "AXTitle" are examples of name object properties.

**Comment by cookiecrook** [comment]
> For the record, iOS has not just an accessible name, but also the possibility of a [list of voice control labels](https://developer.apple.com/news/?id=4dcwl3iv). […] @cookiecrook am I saying this right?

Yes, the proposed Web API for that is ARIA [Issue #1038](https://github.com/w3c/aria/issue/1038) and [PR #174](https://github.com/w3c/aria/pull/1794)

**Comment by maryjom** [comment]
Approved by the AG WG on 11 April.
